// ServiceNow CIS-VR question bank source. Correct answers are listed in "a" (indexes into "o");
// tools/build-banks.js shuffles options deterministically and writes src/data/banks/servicenow-cis-vr.json.
module.exports = {
  id: "servicenow-cis-vr",
  vendor: "ServiceNow",
  code: "CIS-VR",
  name: "Certified Implementation Specialist – Vulnerability Response",
  fullLength: 60,
  minutes: 90,
  passPercent: 70,
  readinessPercent: 85,
  sectioned: false,
  note: "ServiceNow doesn't publish a cut score for CIS-VR; community consensus puts it near 70%. Treat 85% here as your readiness bar. Items marked release-sensitive reference tables, roles, rule names, and workspaces that change between releases; verify them against your own instance.",
  domains: [{"id":"AP","name":"Vulnerability Response Applications and Modules","weight":"25%"},{"id":"DI","name":"Getting Data into Vulnerability Response","weight":"25%"},{"id":"TL","name":"Tools to Manage Vulnerability Response","weight":"23%"},{"id":"AU","name":"Automating Vulnerability Response","weight":"20%"},{"id":"DR","name":"Vulnerability Response Dashboards and Reports","weight":"7%"}],
  Q: [
{d:"AP",s:`What is the main goal of ServiceNow Vulnerability Response?`,
o:[`To prioritize and track remediation of vulnerabilities`,`To run network scans in place of commercial vulnerability scanners`,`To block every exploit attempt at the network perimeter automatically`,`To replace the patch management tools used by IT operations teams`],
a:[0],
e:`VR takes findings from scanners and other sources, prioritizes them by risk, and drives remediation through IT workflows. It relies on scanners and patch tools rather than replacing them, and it doesn't block exploits.`},

{d:"AP",s:`What is the difference between a vulnerability and a vulnerable item?`,
o:[`A vulnerability is the weakness; a vulnerable item is that weakness on a CI`,`A vulnerability is found on one CI; a vulnerable item describes the weakness in general`,`A vulnerable item is a patch that has been applied to fix a weakness`,`There's no difference; both terms refer to the same record`],
a:[0],
e:`A vulnerability, such as a CVE, describes the weakness. A vulnerable item (VI) records that weakness detected on a specific CI, and VIs are what get remediated.`},

{d:"AP",s:`Which record tracks a specific CVE detected on a specific server?`,
o:[`A vulnerable item`,`A vulnerability entry with no CI reference`,`A security incident created for that server`,`A change request raised for the server's owner`],
a:[0],
v:true,
e:`Vulnerable items link a vulnerability to the affected CI. Vulnerability entries describe the weakness generally, and incidents and changes are other processes.`},

{d:"AP",s:`Where does Vulnerability Response get its library of publicly known vulnerabilities?`,
o:[`The National Vulnerability Database (NVD)`,`The instance's knowledge base articles about patches`,`The CMDB Health dashboard for server classes`,`The organization's internal change calendar`],
a:[0],
e:`VR imports CVE data from the NVD, plus vendor-specific entries from scanners. Knowledge articles, CMDB health, and change calendars aren't vulnerability libraries.`},

{d:"AP",s:`What does a CVE identifier represent?`,
o:[`A unique ID for a publicly disclosed vulnerability`,`A score that rates how severe a vulnerability is on a scale of one to ten`,`A category describing the type of software weakness, such as injection`,`A patch released by a vendor to fix several different weaknesses`],
a:[0],
e:`CVE IDs name individual vulnerabilities. CVSS scores severity, CWE classifies weakness types, and patches are solutions.`},

{d:"AP",s:`What does a CVSS score measure?`,
o:[`A vulnerability's technical severity`,`How many devices in your environment have the vulnerability today`,`How critical the affected application is to the business`,`How long remediation is expected to take for the vulnerability`],
a:[0],
e:`CVSS rates the inherent severity of a vulnerability. Exposure, business criticality, and remediation time are separate factors VR combines with it to calculate risk.`},

{d:"AP",s:`What is the CWE?`,
o:[`A catalog of software weakness types`,`A list of exploits currently used by ransomware groups`,`A government database of vendor patches and their release dates`,`A scoring system for the business impact of vulnerabilities`],
a:[0],
e:`The Common Weakness Enumeration classifies types of weaknesses, such as SQL injection. It isn't an exploit list, patch database, or impact score.`},

{d:"AP",s:`Why does Vulnerability Response rely heavily on the CMDB?`,
o:[`The CMDB's CIs supply owners, support groups, and criticality`,`The CMDB stores the raw scan results collected by each scanner`,`The CMDB runs the scans on a schedule for the security team`,`The CMDB decides which CVEs are imported from the NVD`],
a:[0],
e:`Matching VIs to CIs tells VR who should fix them and how important the system is. Raw scan data, scanning, and CVE imports aren't CMDB functions.`},

{d:"AP",s:`Which Security Operations application handles weaknesses found in custom code by application security testing tools?`,
o:[`Application Vulnerability Response`,`Container Vulnerability Response`,`Security Incident Response`,`Configuration Compliance`],
a:[0],
v:true,
e:`Application Vulnerability Response ingests findings from SAST, DAST, and similar tools for applications. Container VR handles container images, SIR handles incidents, and Configuration Compliance handles misconfigurations.`},

{d:"AP",s:`Which application handles vulnerabilities in container images and their running containers?`,
o:[`Container Vulnerability Response`,`Application Vulnerability Response`,`Software Asset Management`,`Security Incident Response`],
a:[0],
v:true,
e:`Container Vulnerability Response brings in findings from container security tools, linking images and running containers to owners. The others address different needs.`},

{d:"AP",s:`What is the role of a vulnerability analyst in VR?`,
o:[`Managing vulnerability data, risk, and exceptions`,`Patching every affected server personally across the company`,`Approving all changes raised by the infrastructure teams`,`Configuring the network scanners' hardware appliances`],
a:[0],
v:true,
e:`Analysts triage and manage vulnerability data and approve or review exceptions. Remediation owners in IT do the fixing, change approvals belong to change management, and scanner hardware isn't the analyst's job.`},

{d:"AP",s:`Who typically fixes vulnerable items in VR?`,
o:[`Remediation owners in IT, such as server teams`,`The vulnerability analysts who imported the scan`,`The scanner vendor's support engineers`,`The external auditors who review the program`],
a:[0],
e:`Remediation is done by the teams that own and support the systems, with VR routing tasks to them. Analysts coordinate, vendors support tools, and auditors review.`},

{d:"AP",s:`Which statement about VR roles is true?`,
o:[`Analysts, remediation owners, and admins have separate roles`,`Every user needs the admin role to view vulnerable items`,`Remediation owners must be given the security analyst role`,`VR has a single role that all users share`],
a:[0],
v:true,
e:`Role separation supports least privilege — remediation owners see their tasks, analysts manage data, admins configure. Admin for everyone or a single shared role isn't how it works.`},

{d:"AP",s:`What are remediation tasks in Vulnerability Response?`,
o:[`Groups of vulnerable items assigned to a team to fix together`,`Individual scanner findings that haven't yet been matched to a CI`,`Exceptions that defer remediation until a future date`,`Reports showing remediation progress to executives`],
a:[0],
v:true,
e:`Remediation tasks (formerly vulnerability groups) bundle related VIs — for example, by solution and assignment group — so teams work them efficiently.`},

{d:"AP",s:`Why group vulnerable items into remediation tasks instead of assigning each one separately?`,
o:[`One fix often resolves many items, so grouping cuts effort`,`The platform can't assign individual vulnerable items to anyone`,`Grouping hides low-risk vulnerable items from dashboards`,`Grouped items no longer need to be rescanned after fixes`],
a:[0],
e:`A single patch might fix the same vulnerability on hundreds of servers, so grouping avoids hundreds of separate tickets. VIs can be assigned individually, grouping doesn't hide anything, and rescanning still confirms fixes.`},

{d:"AP",s:`What does Vulnerability Solution Management help with?`,
o:[`Identifying the fix that resolves a set of vulnerabilities`,`Writing custom exploits to test whether fixes are needed`,`Scheduling network scans for each subnet in the company`,`Calculating the license cost of each scanner integration`],
a:[0],
v:true,
e:`Solution management associates vulnerabilities with their remediating solutions (often patches), including superseded ones, so teams apply the right fix. Exploit writing, scan scheduling, and licensing are unrelated.`},

{d:"AP",s:`Why does it matter that one patch can supersede another?`,
o:[`Teams can apply the latest patch instead of every older one`,`Superseded patches must be installed before newer patches`,`Superseded patches increase a vulnerability's CVSS score`,`Supersedence means the vulnerability can't be fixed at all`],
a:[0],
e:`If a newer patch includes earlier fixes, applying it resolves the older vulnerabilities too, reducing work.`},

{d:"AP",s:`How does Vulnerability Response relate to Security Incident Response?`,
o:[`They're separate apps that can link when a weakness is exploited`,`They're the same application with two different names`,`VR replaces SIR for any incident involving malware`,`They can't share any data because they're licensed separately`],
a:[0],
e:`VR manages weaknesses before they're exploited; SIR manages incidents. If an incident exploited a known vulnerability, the records can be linked.`},

{d:"AP",s:`What does a vulnerable item's risk score represent?`,
o:[`A calculated priority combining severity, exploitability, and impact`,`The number of days since the scanner first detected the vulnerability`,`The CVSS base score copied directly from the NVD with no changes`,`The total number of CIs affected by the same vulnerability`],
a:[0],
v:true,
e:`Risk scores blend factors such as CVSS, exploit availability, and asset criticality so teams fix what matters most. Age, raw CVSS alone, and CI counts are inputs or separate metrics.`},

{d:"AP",s:`Why prioritize by risk rather than by CVSS score alone?`,
o:[`CVSS doesn't reflect active exploitation or asset criticality`,`CVSS scores are always wrong for Windows vulnerabilities`,`Risk scores are required by the NVD for every vulnerability`,`CVSS scores change every day for every vulnerability`],
a:[0],
e:`A high-CVSS vulnerability on an isolated test server may matter less than a medium one being actively exploited on a payment system. CVSS is still a useful input.`},

{d:"AP",s:`What does it mean when a vulnerability appears in CISA's Known Exploited Vulnerabilities catalog?`,
o:[`Attackers are known to be exploiting it, so it's urgent`,`The vulnerability has been fixed by every affected vendor`,`The vulnerability only affects US government systems`,`The vulnerability's CVSS score has been set to zero`],
a:[0],
e:`KEV lists vulnerabilities with evidence of active exploitation, which strongly raises urgency. It doesn't mean they're fixed, government-only, or unscored.`},

{d:"AP",s:`What is the purpose of the Vulnerability Response workspaces?`,
o:[`Role-focused views for managing and remediating vulnerabilities`,`A separate database that stores scanner data outside the CMDB`,`A training environment for analysts who are new to VR`,`A public portal where vendors post new vulnerabilities`],
a:[0],
v:true,
e:`Workspaces give analysts and remediation owners focused views of their work with relevant actions. They aren't separate databases, training sandboxes, or vendor portals.`},

{d:"AP",s:`What's the benefit of giving remediation owners their own view of assigned work?`,
o:[`They see only what they must fix, with context and due dates`,`They can approve their own exceptions without any review`,`They can change risk scores to lower their workload`,`They no longer need to update task status when work is done`],
a:[0],
e:`Focused views help IT teams act on their tasks. Self-approving exceptions, editing scores, or skipping updates would undermine the program.`},

{d:"AP",s:`How does VR fit with the rest of the ServiceNow platform?`,
o:[`It uses shared data, like the CMDB and change, to drive fixes`,`It runs on a separate instance from IT service management`,`It can only send email to IT teams about each vulnerability`,`It replaces change management for any patch it recommends`],
a:[0],
e:`VR's value comes from using platform data and workflows: the CMDB for context, assignment for routing, and change management for controlled remediation.`},

{d:"AP",s:`Which Security Operations capability focuses on misconfigurations, such as weak settings, rather than software vulnerabilities?`,
o:[`Configuration Compliance`,`Container Vulnerability Response`,`Application Vulnerability Response`,`Threat Intelligence`],
a:[0],
v:true,
e:`Configuration Compliance handles findings from configuration assessment tools. The other applications address containers, application code, and threat data.`},

{d:"AP",s:`An application vulnerable item comes from a code scanner. What does it usually link to?`,
o:[`The application or code component that has the weakness`,`A physical server's serial number in the asset register`,`The user who most recently logged in to the application`,`A firewall rule protecting the application from attacks`],
a:[0],
v:true,
e:`Application findings belong to the application or component so development owners can fix them. Server serials, user logins, and firewall rules aren't where code flaws live.`},

{d:"AP",s:`Who typically remediates application vulnerabilities found in custom code?`,
o:[`The development team that owns the application`,`The network team that manages the firewalls`,`The service desk that handles password resets`,`The facilities team that manages the datacenter`],
a:[0],
e:`Code flaws are fixed by developers. Network, service desk, and facilities teams don't change application code.`},

{d:"AP",s:`Why should vulnerable items be linked to the business services their CIs support?`,
o:[`It shows business impact and helps prioritize remediation`,`It lets business users close vulnerable items themselves`,`It removes the need to match items to individual CIs`,`It makes every linked vulnerable item critical by default`],
a:[0],
e:`Service context reveals which vulnerabilities threaten important services. Business users don't close VIs, CI matching is still needed, and not everything becomes critical.`},

{d:"AP",s:`What happens to a vulnerable item when a rescan shows the vulnerability is no longer present?`,
o:[`It can close automatically as fixed`,`It's deleted along with its history`,`It stays open until an auditor closes it`,`It's converted into a security incident`],
a:[0],
v:true,
e:`Scanner confirmation that a vulnerability is gone typically closes the VI as fixed, keeping history. Deleting, waiting for auditors, or creating incidents isn't the default.`},

{d:"AP",s:`What's the purpose of the "first found" and "last found" dates on vulnerable items?`,
o:[`They show how long it has existed and whether it's still detected`,`They set the date the patch will be installed by IT operations`,`They show when the analyst was hired and their last review`,`They record when the CVE was first published by the NVD`],
a:[0],
v:true,
e:`First and last found dates track a VI's age and current presence, which feed remediation targets and staleness checks. They aren't patch schedules, staff dates, or CVE publication dates.`},

{d:"AP",s:`What should happen if a vulnerable item hasn't been seen by the scanner for a long time?`,
o:[`Handle it by policy, such as closing it as stale`,`Leave it open forever in case it reappears`,`Raise its risk score to critical automatically`,`Assign it to the CISO for personal review`],
a:[0],
v:true,
e:`Items not seen in many scans may be fixed or decommissioned, so policies close or review them. Leaving them open inflates backlogs, and the other options don't fit.`},

{d:"AP",s:`Which team usually owns the configuration of Vulnerability Response itself?`,
o:[`The VR admin or platform team, with security input`,`Each remediation owner, for their own assigned items`,`The scanner vendor, through their support portal`,`Every employee who uses the ServiceNow portal`],
a:[0],
e:`VR configuration — rules, integrations, calculators — belongs to admins working with the security team. Remediation owners, vendors, and end users don't configure the application.`},

{d:"AP",s:`Why might the same CVE produce vulnerable items on hundreds of CIs?`,
o:[`The software is installed on many systems`,`The scanner duplicates every finding by mistake`,`The NVD assigns each CVE to hundreds of CIs`,`Each CI reports the CVE once per user`],
a:[0],
e:`Widely deployed software creates the same weakness everywhere it's installed. That's why grouping by solution is so useful.`},

{d:"AP",s:`What does "time to remediate" measure?`,
o:[`How long it takes to fix vulnerable items after they're found`,`How long a scanner takes to complete a full network scan`,`How long the NVD takes to publish a new CVE after discovery`,`How long it takes analysts to log in to the workspace`],
a:[0],
e:`Time to remediate tracks how quickly the organization closes VIs, a key VR performance measure. Scan duration, publication delay, and logins are other things.`},

{d:"AP",s:`What is a remediation owner's main responsibility in VR?`,
o:[`Fixing assigned vulnerabilities or requesting exceptions`,`Approving exceptions requested by other remediation owners`,`Importing new CVEs from the NVD each night`,`Configuring the vulnerability risk calculators`],
a:[0],
e:`Owners act on their tasks: patch, mitigate, or request an exception when they can't. Approvals, imports, and calculator configuration belong to other roles.`},

{d:"AP",s:`Why can't every vulnerability be fixed immediately?`,
o:[`Fixes need testing and maintenance windows, or may not exist yet`,`Vulnerability Response limits each team to one fix per month`,`The NVD prevents organizations from fixing new vulnerabilities`,`Scanners stop detecting vulnerabilities after one week`],
a:[0],
e:`Patches may break applications, require downtime, or not be available yet, which is why prioritization and exceptions exist.`},

{d:"AP",s:`What does mean time to remediate by risk rating show leadership?`,
o:[`Whether the riskiest items are fixed fastest`,`How many scanners the organization currently licenses`,`Which analysts have closed the most vulnerable items`,`How many CVEs the NVD published during the period`],
a:[0],
e:`Breaking remediation time down by risk shows whether the program is focusing on what matters. Scanner counts, individual analysts, and NVD volume don't answer that.`},

{d:"AP",s:`What's the advantage of handling vulnerabilities in ServiceNow rather than in each scanner's own console?`,
o:[`Findings from many tools are prioritized and tracked in one place`,`Scanners stop working once their data is imported into the platform`,`ServiceNow finds vulnerabilities that scanners can't detect`,`Each scanner's console becomes read-only after integration`],
a:[0],
e:`VR unifies data across scanners and connects it to owners and workflows. Scanners keep working, and VR doesn't detect vulnerabilities on its own.`},

{d:"DI",s:`How do findings from scanners such as Qualys, Tenable, or Rapid7 usually get into Vulnerability Response?`,
o:[`Through Store integrations that import scan data on a schedule`,`By analysts typing each finding into a new vulnerable item record`,`By emailing the scanner's PDF reports to the instance mailbox`,`By copying scanner databases directly into the CMDB tables`],
a:[0],
v:true,
e:`Certified scanner integrations import findings, hosts, and vulnerability details automatically. Manual entry, emailed reports, and direct database copies don't scale or keep data consistent.`},

{d:"DI",s:`What must happen for a scanner finding to become a vulnerable item on the right CI?`,
o:[`The scanned host must be matched to a CI`,`The CVE must be manually approved by an auditor`,`The scanner must be installed on the instance`,`The CI must be deleted and recreated first`],
a:[0],
e:`VR identifies which CI a scanned host corresponds to before creating the VI. Without matching, there's no owner or context.`},

{d:"DI",s:`What does VR use to match scanned hosts to existing CIs?`,
o:[`CI lookup rules matching on IP, hostname, and similar`,`The scanner's own list of CI sys_ids, sent with every finding`,`A manual assignment by the analyst for every host in each scan`,`The order in which hosts appear in the scanner's report`],
a:[0],
v:true,
e:`Lookup rules (and IRE-based identification) compare scanner host data — IP, FQDN, MAC, scanner IDs — with CMDB attributes. Scanners don't know sys_ids, manual matching doesn't scale, and order is meaningless.`},

{d:"DI",s:`A scanned host can't be matched to any CI. What typically happens?`,
o:[`It's held as unmatched or creates a CI by policy`,`The finding is silently discarded with no record kept`,`It's matched to the first CI alphabetically by name`,`The whole import fails until the host is fixed`],
a:[0],
v:true,
e:`Unmatched hosts are kept for review or, depending on configuration, used to create CIs. Discarding data, random matching, or failing the import would be harmful.`},

{d:"DI",s:`Why is a high number of unmatched hosts a concern?`,
o:[`Their vulnerabilities have no owner and may never get fixed`,`Unmatched hosts slow the scanner's next network scan`,`Unmatched hosts are automatically marked as false positives`,`Unmatched hosts double the CVSS score of their vulnerabilities`],
a:[0],
e:`Without a CI, there's no assignment or business context, so risk sits unaddressed. Scanner speed, false positives, and scoring aren't affected.`},

{d:"DI",s:`What is the best long-term fix for many unmatched hosts?`,
o:[`Improve CMDB coverage and identifying data`,`Delete unmatched findings after every import`,`Stop scanning hosts that can't be matched`,`Assign all unmatched items to one analyst`],
a:[0],
e:`Better discovery and consistent identifiers let VR match hosts. Deleting findings or stopping scans hides risk, and dumping items on one person doesn't fix the cause.`},

{d:"DI",s:`What does importing NVD data add to Vulnerability Response?`,
o:[`CVE details like descriptions and CVSS scores`,`A list of every device on the internet that has each CVE`,`Patches that install themselves on affected servers`,`Remediation tasks assigned automatically to IT teams`],
a:[0],
e:`The NVD provides authoritative vulnerability details. It doesn't inventory devices, install patches, or create tasks.`},

{d:"DI",s:`Why do scanners often provide their own vulnerability entries in addition to CVEs?`,
o:[`They detect issues without a CVE and add their own context`,`CVEs are never accurate enough to be used by scanners`,`Scanner entries replace the need for the NVD entirely`,`Scanner entries can only be used for container findings`],
a:[0],
v:true,
e:`Scanner-specific entries (third-party vulnerabilities) cover detections such as missing configuration or vendor-specific checks, mapped to CVEs where possible.`},

{d:"DI",s:`What's an advantage of scheduling scanner imports to run regularly?`,
o:[`New findings and fixes appear in VR without manual work`,`Scheduled imports bypass all CI matching rules`,`Scheduled imports delete fixed vulnerabilities from the scanner`,`Scheduled imports guarantee no false positives are imported`],
a:[0],
e:`Regular imports keep VR current, so new vulnerabilities are prioritized and fixed ones close. Matching still applies, scanners aren't altered, and false positives can still occur.`},

{d:"DI",s:`An import of scanner data fails partway. Where should an admin look first?`,
o:[`The integration run history and errors`,`The CMDB Health score for the server class`,`The knowledge base articles about patching`,`Each remediation owner's notification settings`],
a:[0],
v:true,
e:`Integration run records show what was processed and why failures happened, such as credentials or API errors. The other options don't track imports.`},

{d:"DI",s:`Which kind of tool feeds Application Vulnerability Response?`,
o:[`Application security testing tools, such as SAST and DAST`,`Network firewalls that log blocked connections to applications`,`HR systems that track which developers wrote each application`,`Backup tools that copy application data each night`],
a:[0],
v:true,
e:`AVR ingests findings from static and dynamic testing tools and similar sources. Firewall logs, HR data, and backups aren't vulnerability findings.`},

{d:"DI",s:`Which kind of tool feeds Container Vulnerability Response?`,
o:[`Container security tools scanning images`,`Email security gateways that scan attachments`,`Endpoint backup agents on employee laptops`,`Web proxies that filter employee browsing`],
a:[0],
v:true,
e:`Container security platforms report vulnerabilities in images and running containers. The other tools address different security areas.`},

{d:"DI",s:`How does enrichment add value to imported vulnerabilities?`,
o:[`It adds context like exploit availability and threat intelligence`,`It increases every vulnerability's CVSS score by one point`,`It deletes vulnerabilities that don't affect Windows systems`,`It assigns every vulnerability to the security team`],
a:[0],
e:`Enrichment adds information — known exploits, threat activity, vendor details — that improves prioritization. It doesn't inflate scores, filter by platform, or assign everything to security.`},

{d:"DI",s:`Why might an organization integrate more than one scanner with VR?`,
o:[`Different scanners cover different assets`,`The platform requires at least three scanners to work`,`Using more scanners lowers every vulnerability's risk score`,`Multiple scanners remove the need for a CMDB`],
a:[0],
e:`Organizations often use specialized scanners for different environments. VR consolidates them. There's no minimum, scores aren't lowered, and the CMDB remains essential.`},

{d:"DI",s:`Two scanners report the same vulnerability on the same server. What's the desired outcome in VR?`,
o:[`One vulnerable item, with both sources recorded`,`Two separate items assigned to two different teams`,`Neither item is imported because they conflict`,`The item with the lower score is deleted`],
a:[0],
v:true,
e:`Consolidating duplicate detections avoids double work while keeping each source's evidence. How this is handled can depend on configuration.`},

{d:"DI",s:`What information is typically needed to configure a scanner integration?`,
o:[`The scanner's API URL, credentials, and import schedule`,`Every employee's email address and phone number`,`The CVSS score for each vulnerability you expect to find`,`The serial number of the scanner vendor's own servers`],
a:[0],
e:`Integrations need to know where to connect, how to authenticate, and when to run. Employee details, expected scores, and vendor hardware aren't required.`},

{d:"DI",s:`A scanner sits inside the corporate network and isn't reachable from the internet. How can VR import from it?`,
o:[`Through a MID Server in the network`,`By opening the scanner to the public internet`,`By emailing exports to analysts each day`,`It can't; only cloud scanners are supported`],
a:[0],
e:`MID Servers relay data from internal systems securely. Exposing the scanner or emailing exports creates risk and manual effort.`},

{d:"DI",s:`What does the "last found" date on a vulnerable item rely on?`,
o:[`Regular scans that detect the vulnerability again`,`The analyst updating the date by hand each week`,`The NVD's publication date for the CVE`,`The remediation task's due date`],
a:[0],
e:`Each scan that sees the vulnerability updates the last found date, which supports staleness and closure logic. It isn't manual or tied to NVD or task dates.`},

{d:"DI",s:`Why is authenticated scanning generally preferred over unauthenticated scanning?`,
o:[`It sees installed software more accurately`,`It doesn't need any credentials to run`,`It scans only the internet-facing systems`,`It can't produce false positives at all`],
a:[0],
e:`With credentials, scanners inspect hosts directly, finding missing patches more reliably. It needs credentials by definition, isn't limited to external systems, and can still produce false positives.`},

{d:"DI",s:`What does importing asset data from a scanner — not just vulnerabilities — help with?`,
o:[`Matching hosts to CIs and finding CMDB gaps`,`Replacing Discovery as the CMDB's only data source`,`Automatically patching every asset the scanner finds`,`Calculating the purchase cost of each scanned asset`],
a:[0],
e:`Host details help identification and can reveal coverage gaps. Scanners don't replace Discovery, patch assets, or provide financial data.`},

{d:"DI",s:`What is a vulnerability's "solution" in VR?`,
o:[`The remediation that fixes it, often a specific patch`,`The workaround analysts use to hide it from reports`,`The name of the scanner that found it first`,`The date the vulnerable item will be closed`],
a:[0],
v:true,
e:`Solutions describe how to remediate, such as applying a vendor update. They aren't ways to hide findings, scanner names, or closure dates.`},

{d:"DI",s:`Why do vulnerability imports benefit from accurate business criticality on CIs?`,
o:[`It feeds risk scores, prioritizing critical systems`,`It decides which scanner is allowed to scan each CI`,`It sets the CVSS score for each vulnerability found`,`It determines how often the NVD publishes updates`],
a:[0],
e:`Criticality is a key risk input. It doesn't control scanners, CVSS, or NVD timing.`},

{d:"DI",s:`What should be validated after configuring a new scanner integration?`,
o:[`That findings import, match to CIs, and look right`,`That the scanner's logo appears on the vulnerability form`,`That every vulnerable item is assigned to the same group`,`That no vulnerabilities are found in the first import`],
a:[0],
e:`Check that imports work end to end and that matching and field values are accurate. Logos, uniform assignment, and zero findings aren't success criteria.`},

{d:"DI",s:`What is threat intelligence used for during vulnerability enrichment?`,
o:[`Showing which vulnerabilities attackers are actively using`,`Writing patches for vulnerabilities vendors haven't fixed`,`Removing vulnerabilities from the scanner's database`,`Identifying which employees reported each vulnerability`],
a:[0],
e:`Threat intelligence highlights exploitation in the wild, which raises priority. It doesn't produce patches, change scanners, or track reporters.`},

{d:"DI",s:`An organization wants to bring in vulnerabilities from a tool with no Store integration. What's a reasonable approach?`,
o:[`Build an import using the platform's integration tools`,`Ask analysts to copy findings from the tool by hand`,`Ignore the tool's findings until an integration appears`,`Replace the tool with a spreadsheet of known issues`],
a:[0],
e:`Custom imports through standard integration features can bring in any source. Manual copying, ignoring findings, or spreadsheets leave gaps.`},

{d:"DI",s:`Why are cloud assets sometimes hard to match to CIs?`,
o:[`They're short-lived and their IPs change often`,`Cloud assets can't be stored in the CMDB at all`,`Scanners can never scan cloud workloads`,`Cloud providers forbid vulnerability scanning`],
a:[0],
e:`Ephemeral instances and changing addresses make identification harder, so cloud-specific identifiers and discovery help. Cloud assets can be in the CMDB, scanned, and assessed.`},

{d:"DI",s:`What does a scanner's plugin or QID typically identify?`,
o:[`The check that detected it`,`The analyst who reviewed the vulnerable item`,`The CI's business owner in the CMDB`,`The date the patch will be deployed`],
a:[0],
v:true,
e:`Scanner plugin IDs (Tenable) or QIDs (Qualys) identify the detection check, which maps to vulnerability entries. They don't identify people, owners, or dates.`},

{d:"DI",s:`What does it mean if a vulnerable item's CI is retired in the CMDB?`,
o:[`It may no longer apply and should be reviewed`,`The item's risk score should be raised to the maximum`,`The item should be reassigned to the CISO`,`Nothing; retired CIs don't affect vulnerable items`],
a:[0],
e:`Vulnerabilities on decommissioned assets don't need remediation, so they should be reviewed and closed per policy.`},

{d:"DI",s:`How often should scanner imports typically run?`,
o:[`Matching scan schedules, like daily or weekly`,`Once a year, before the external audit`,`Only when a major vulnerability is announced`,`Never; data should be imported manually`],
a:[0],
e:`Import frequency should keep pace with scanning so VR reflects current exposure. Annual or ad hoc imports leave VR out of date.`},

{d:"DI",s:`What does "detection" mean in Vulnerability Response?`,
o:[`A scanner observation of a vulnerability on an asset`,`An analyst's approval of a vulnerability exception`,`A patch being installed on an affected server`,`A remediation task being assigned to a team`],
a:[0],
v:true,
e:`Detections are the individual observations from scans that roll up into vulnerable items. Approvals, installations, and assignments are later steps.`},

{d:"DI",s:`Why keep scanner credentials in a secure credential store rather than in scripts?`,
o:[`To protect them and allow easy rotation`,`Because scripts can't connect to external systems`,`Because credential stores make imports run faster`,`So every user can read the scanner password`],
a:[0],
e:`Secure storage limits exposure and simplifies rotation. Scripts can connect, credential stores don't speed things up, and passwords shouldn't be widely visible.`},

{d:"DI",s:`What is a good reason to scope scanner imports to certain asset groups at first?`,
o:[`To validate matching and data quality before scaling up`,`Because integrations can import only one host at a time`,`Because full imports delete existing vulnerable items`,`To prevent critical servers from being assessed`],
a:[0],
e:`Starting small makes it easier to find matching and mapping problems. Integrations handle many hosts, full imports don't delete items, and critical servers should be assessed.`},

{d:"DI",s:`How does the CMDB's "managed by group" help when vulnerabilities are imported?`,
o:[`It can be used to route remediation to the right team`,`It decides whether the vulnerability is imported at all`,`It sets the scanner's scan schedule for the CI`,`It changes the vulnerability's CVSS score`],
a:[0],
e:`Assignment rules often use CI support or managed-by groups to route work. It doesn't filter imports, schedule scans, or change scores.`},

{d:"DI",s:`What does Container Vulnerability Response link vulnerabilities to?`,
o:[`Images and the containers that use them`,`Physical servers' serial numbers only`,`Users' laptops that run container tools`,`Network switches that route container traffic`],
a:[0],
v:true,
e:`Container findings relate to images and their running instances, so owners can rebuild images. Serial numbers, laptops, and switches aren't the target.`},

{d:"DI",s:`What's the main risk of importing scan data without good CI matching?`,
o:[`Duplicate or orphaned items that no one owns or fixes`,`The scanner's license being cancelled by the vendor`,`The NVD refusing to share further CVE data`,`Every vulnerability being marked as critical`],
a:[0],
e:`Poor matching creates noise and ownerless risk. Licensing, NVD access, and severity aren't affected.`},

{d:"DI",s:`Why record which source reported each vulnerable item?`,
o:[`To trace findings back and judge source reliability`,`To bill each scanner vendor for the items found`,`To hide items from sources that are less reliable`,`Because items can't be closed without a source`],
a:[0],
e:`Source attribution supports troubleshooting and validation. It isn't for billing or hiding findings, and closure depends on remediation evidence.`},

{d:"DI",s:`What should happen when the NVD updates a CVE's CVSS score?`,
o:[`VR updates the vulnerability, and risk recalculates`,`Existing vulnerable items keep the old score forever`,`The CVE is deleted and imported again as new`,`Analysts must re-enter every affected item by hand`],
a:[0],
v:true,
e:`Updated NVD data flows into VR so risk reflects current information. Keeping stale scores, deleting CVEs, or manual re-entry isn't how it works.`},

{d:"TL",s:`What do assignment rules do in Vulnerability Response?`,
o:[`Route vulnerable items or tasks to the right group`,`Decide which CVEs are imported from the NVD each night`,`Set the CVSS score for vulnerabilities without one`,`Choose which scanner scans each subnet in the network`],
a:[0],
v:true,
e:`Assignment rules use conditions — often CI support group or ownership — to route work. They don't control imports, scoring, or scanning.`},

{d:"TL",s:`What do remediation task rules define?`,
o:[`How vulnerable items are grouped into remediation tasks`,`How long each scanner import is allowed to run`,`Which analysts are allowed to approve exceptions`,`Which dashboards appear in the vulnerability workspace`],
a:[0],
v:true,
e:`Remediation task rules group VIs — for example, by solution, assignment group, or CI — so teams get efficient work units. The other options belong to other configurations.`},

{d:"TL",s:`What do remediation target rules set?`,
o:[`Due dates for fixing items, often based on risk`,`The patch file each server should install next`,`The scanner that's allowed to detect each CVE`,`The color of vulnerable items in list views`],
a:[0],
v:true,
e:`Target rules assign remediation due dates — for example, 7 days for critical, 30 for high — which drive SLA-style tracking. They don't pick patches, scanners, or colors.`},

{d:"TL",s:`What do vulnerability calculators do?`,
o:[`Calculate risk scores and ratings from defined inputs`,`Count the number of scanners connected to the instance`,`Estimate how long a full network scan will take`,`Calculate each remediation owner's performance bonus`],
a:[0],
v:true,
e:`Calculators combine factors such as CVSS, exploitability, and asset criticality into risk scores and ratings that drive prioritization. The other options aren't calculator functions.`},

{d:"TL",s:`An organization wants vulnerabilities with known exploits to rank higher. Where should this be configured?`,
o:[`In the risk calculator rules`,`In each scanner's own scan policy`,`In the NVD's published CVSS scores`,`In the remediation owner's preferences`],
a:[0],
v:true,
e:`Calculator rules can weight exploit availability, raising risk for exploited vulnerabilities. Scanner policies, NVD data, and user preferences don't set VR priority.`},

{d:"TL",s:`What do classification or filter rules help VR do?`,
o:[`Categorize items so they're handled consistently`,`Delete vulnerabilities that come from low-priority scanners`,`Hide vulnerable items from the remediation owners`,`Encrypt vulnerability data stored in the CMDB`],
a:[0],
v:true,
e:`Classification rules group or tag items by criteria — such as end-of-life software — so downstream rules handle them appropriately. They don't delete, hide, or encrypt data.`},

{d:"TL",s:`A critical vulnerability on a payment server should be fixed within 7 days, but a low one on a test server within 90. What makes this happen?`,
o:[`Remediation target rules based on risk rating`,`A single due date applied to every vulnerability`,`Asking each owner to choose their own deadline`,`Scanner policies that delay low-risk findings`],
a:[0],
e:`Risk-based target rules set appropriate deadlines automatically. One-size-fits-all dates, self-chosen deadlines, or scanner delays don't reflect risk.`},

{d:"TL",s:`Why is the order of assignment rules important?`,
o:[`The first matching rule usually decides the assignment`,`Rules only run in alphabetical order by name`,`Later rules delete assignments made by earlier ones`,`Order determines how often scans run`],
a:[0],
v:true,
e:`Like many rule engines, assignment rules evaluate in order, so more specific rules should come first. Alphabetical order, deletion, and scan frequency aren't factors.`},

{d:"TL",s:`A vulnerable item matches no assignment rule. What should happen?`,
o:[`A default assignment routes it for triage`,`It's deleted because nobody can fix it`,`It's closed automatically as a false positive`,`It's assigned to every group at once`],
a:[0],
e:`A fallback assignment ensures nothing sits unowned. Deleting, closing, or assigning to everyone causes lost risk or confusion.`},

{d:"TL",s:`What's a sensible way to group vulnerable items for a Windows server team?`,
o:[`By solution (patch) and the team's assignment group`,`By the alphabetical order of the CVE descriptions`,`By the day of the week each item was detected`,`By the analyst who imported the scan`],
a:[0],
e:`Grouping by fix and team gives tasks the team can act on in one change. Alphabetical, weekday, or importer grouping isn't actionable.`},

{d:"TL",s:`What is the vulnerability manager's workspace mainly used for?`,
o:[`Overseeing risk, exceptions, and progress`,`Writing patches for vendor software`,`Configuring scanner hardware appliances`,`Managing employee onboarding tasks`],
a:[0],
v:true,
e:`The workspace gives vulnerability managers an overview of exposure, queues, and exceptions to manage the program. Writing patches, configuring hardware, and onboarding aren't VR tasks.`},

{d:"TL",s:`How do remediation owners usually work their vulnerability tasks?`,
o:[`Through a remediation-focused workspace or task list`,`By logging in to each scanner's console separately`,`By reading weekly PDF reports from the security team`,`By editing CMDB records to remove vulnerabilities`],
a:[0],
v:true,
e:`Owners work from focused views of assigned tasks with context and due dates. Scanner consoles and PDFs are fragmented, and editing the CMDB doesn't fix anything.`},

{d:"TL",s:`Why should calculator inputs include asset criticality?`,
o:[`So vulnerabilities on critical assets are prioritized`,`So scanners scan critical assets more often`,`So the NVD publishes CVEs faster for critical assets`,`So critical assets don't need remediation tasks`],
a:[0],
e:`Weighting by criticality focuses effort where business impact is greatest. It doesn't affect scanning frequency, NVD publication, or the need to remediate.`},

{d:"TL",s:`What's the effect of changing a risk calculator's rules?`,
o:[`Scores recalculate, changing priorities and dates`,`All existing vulnerable items are deleted and imported again`,`Every scanner integration must be reinstalled from the Store`,`Nothing changes for items that already exist in VR`],
a:[0],
v:true,
e:`Calculator changes flow through to scores and anything that depends on them, such as targets. Test changes before applying them broadly.`},

{d:"TL",s:`What is a vulnerability's "risk rating" used for?`,
o:[`A simple label, like critical or high, used for prioritization`,`The number of scanners that have detected the vulnerability`,`The vendor's estimate of how hard the patch is to install`,`The date the vulnerability will be closed`],
a:[0],
e:`Ratings bucket risk scores into labels that drive targets, reporting, and attention. They aren't counts, vendor estimates, or dates.`},

{d:"TL",s:`Several teams own different parts of a server. How can VR route vulnerabilities to the right team?`,
o:[`Assignment rules that consider the software or component affected`,`Assign all of the server's items to the team that owns the hardware`,`Let every team pick items from a shared queue as they see fit`,`Create a separate CI for each team that touches the server`],
a:[0],
v:true,
e:`Rules can route by affected software — for example, database vulnerabilities to the DBA team — rather than by host alone. Defaulting to one team, free-for-all queues, or fake CIs cause confusion.`},

{d:"TL",s:`Why should remediation target dates be visible to remediation owners?`,
o:[`So they can plan work to meet deadlines`,`So they can change the dates to suit them`,`So they can close items without fixing them`,`So they can lower the risk ratings`],
a:[0],
e:`Visible targets help owners prioritize. Changing dates, closing unfixed items, or lowering ratings should go through proper processes.`},

{d:"TL",s:`What happens when a remediation target date passes without a fix?`,
o:[`The item is flagged overdue and escalated`,`The item is closed automatically as resolved`,`The item's risk score drops to zero`,`The item is deleted from the workspace`],
a:[0],
v:true,
e:`Overdue items should be visible and escalated. Auto-closing, zeroing scores, or deleting would hide unmanaged risk.`},

{d:"TL",s:`What's the benefit of rule-based configuration in VR over manual triage?`,
o:[`Consistent, scalable handling of large volumes of findings`,`Rules remove the need to ever review the program again`,`Rules make the scanner find fewer vulnerabilities`,`Rules let remediation owners skip patch testing`],
a:[0],
e:`Rules apply the same logic to thousands of items. Programs still need review, rules don't change detection, and testing still matters.`},

{d:"TL",s:`Why might remediation tasks be grouped by CI instead of by solution?`,
o:[`When one team fixes all issues on a server in one maintenance window`,`Because grouping by solution isn't supported in Vulnerability Response`,`Because grouping by CI deletes the solution information from items`,`To ensure each vulnerable item ends up in several remediation tasks`],
a:[0],
e:`Grouping choices depend on how teams work — some patch by host, others by fix. Both are possible, solution data isn't lost, and items shouldn't be duplicated.`},

{d:"TL",s:`What does a risk score threshold for "critical" in the calculator determine?`,
o:[`Which items are labeled critical`,`Which scanners are allowed to report critical findings`,`Which CVEs the NVD marks as critical`,`Which users can view critical items`],
a:[0],
v:true,
e:`Thresholds map scores to ratings. Scanners, NVD labels, and visibility are controlled elsewhere.`},

{d:"TL",s:`An analyst notices vulnerable items routed to a team that was disbanded. What should be fixed?`,
o:[`The assignment rules or CI data`,`The NVD import schedule`,`The scanner's credentials`,`The vulnerability calculator`],
a:[0],
e:`Outdated routing comes from rules or CMDB ownership data. NVD schedules, credentials, and calculators don't control assignment.`},

{d:"TL",s:`What's the advantage of showing related solutions on a remediation task?`,
o:[`It shows owners exactly which fix resolves the items`,`It lets owners close tasks without applying the fix`,`It increases the task's risk score automatically`,`It hides the CVE details from the owner`],
a:[0],
e:`Knowing the fix speeds remediation. It doesn't allow closure without fixing, change scores, or hide details.`},

{d:"TL",s:`How can VR handle vulnerabilities in end-of-life software that will never get a patch?`,
o:[`Route them for upgrade, replacement, or exception`,`Wait for the vendor to release a patch, however long it takes`,`Lower their risk score to zero because no fix exists`,`Delete them because they can't be remediated`],
a:[0],
e:`EOL software needs a different response: upgrade, replace, isolate, or a formal exception. Waiting, zeroing, or deleting ignores the risk.`},

{d:"TL",s:`What does the "state" of a vulnerable item, such as open, in review, or closed, help with?`,
o:[`Tracking each item's lifecycle`,`Setting the item's CVSS score`,`Deciding which scanner found the item`,`Choosing which instance stores the item`],
a:[0],
v:true,
e:`States show progress and drive automation and reporting. CVSS, source, and storage aren't determined by state.`},

{d:"TL",s:`Why test new assignment or grouping rules before activating them?`,
o:[`Bad rules could misroute thousands of items at once`,`Rules can't be deactivated once they're activated`,`Testing increases the number of rules allowed`,`Untested rules delete vulnerable items`],
a:[0],
e:`Rules act at scale, so mistakes spread quickly. Rules can be deactivated, testing doesn't change limits, and untested rules don't inherently delete data.`},

{d:"TL",s:`How can managers see which teams have the most overdue vulnerabilities?`,
o:[`By reporting overdue items by group`,`By asking each team lead in a weekly meeting`,`By counting rows in each scanner's console`,`By reading the NVD's monthly summary`],
a:[0],
e:`Overdue reporting by assignment group shows where to focus. Meetings, scanner consoles, and NVD summaries don't reflect your remediation status.`},

{d:"TL",s:`What's the purpose of reassigning a remediation task?`,
o:[`Moving it to the team that can actually fix it`,`Resetting the remediation target date to a later one`,`Lowering the risk rating of every item in the task`,`Closing the vulnerable items it contains`],
a:[0],
e:`Reassignment corrects routing. It shouldn't be used to extend deadlines, lower ratings, or close items.`},

{d:"TL",s:`An organization wants internet-facing assets to get higher risk scores. How can this be done?`,
o:[`Include internet exposure in calculator rules`,`Ask the scanner vendor to raise their CVSS scores`,`Move internet-facing servers to a different instance`,`Assign every internet-facing item to the CISO`],
a:[0],
e:`Calculators can use CI attributes such as exposure to raise risk. Vendors don't change CVSS for you, and instances and assignments don't affect scoring.`},

{d:"TL",s:`What's the difference between a vulnerable item's risk score and its CVSS score?`,
o:[`Risk reflects your context; CVSS doesn't`,`They're always the same number`,`CVSS includes business criticality; risk doesn't`,`Risk is set by the NVD; CVSS by your analysts`],
a:[0],
e:`CVSS rates the weakness in general. Risk adjusts for your environment — exploitability, asset criticality, exposure. The NVD provides CVSS, and your calculators set risk.`},

{d:"TL",s:`Why might a remediation task be split into several smaller tasks?`,
o:[`Different parts need different teams or windows`,`Smaller tasks always have lower risk scores`,`The platform limits tasks to one vulnerable item`,`Splitting tasks closes their vulnerable items`],
a:[0],
v:true,
e:`Splitting lets work match how teams operate. Size doesn't change risk, tasks can hold many items, and splitting doesn't close anything.`},

{d:"TL",s:`Which records should a remediation owner update when a fix is deployed?`,
o:[`The remediation task, with notes`,`The NVD entry for the CVE`,`The scanner's plugin definition`,`The calculator's rule conditions`],
a:[0],
e:`Owners record what they did on their task; a rescan then confirms the fix. NVD entries, scanner plugins, and calculators aren't theirs to change.`},

{d:"TL",s:`What happens after a remediation owner marks a task as fixed?`,
o:[`A rescan confirms the fix first`,`The vulnerable items are deleted immediately`,`The CVE is removed from the NVD`,`The CI is retired from the CMDB`],
a:[0],
v:true,
e:`Verification by rescan prevents closing items that aren't actually fixed. Deleting items, changing the NVD, or retiring CIs aren't part of the process.`},

{d:"TL",s:`What is a good reason to review vulnerability rules regularly?`,
o:[`Teams, assets, and threats change`,`Rules expire automatically after 30 days`,`Reviews are needed to keep scanners licensed`,`Rules stop working after each upgrade`],
a:[0],
e:`Organizational and threat changes make rules outdated. They don't expire, affect licensing, or necessarily break on upgrade.`},

{d:"TL",s:`What does it mean if most of a team's vulnerable items are in a "deferred" state?`,
o:[`The team has many approved exceptions`,`The team has fixed all of its vulnerabilities`,`The items were imported from the wrong scanner`,`The items have no CI and can't be assigned`],
a:[0],
v:true,
e:`Deferred items carry accepted risk until exceptions expire, so they deserve attention. They aren't fixed, mis-sourced, or unmatched.`},

{d:"AU",s:`A remediation owner can't patch a server until next quarter. What should they request?`,
o:[`A deferral exception with justification and an expiry date`,`Deletion of the vulnerable items until the patch is ready`,`A change to the CVSS score so the item looks less urgent`,`Reassignment of the items to the security team instead`],
a:[0],
v:true,
e:`Exceptions formally accept risk for a limited time with approval. Deleting items, changing scores, or reassigning to security hides the risk.`},

{d:"AU",s:`What should happen when a vulnerability exception expires?`,
o:[`The items return to active remediation`,`The items are closed as fixed`,`The exception renews automatically`,`The items are deleted`],
a:[0],
v:true,
e:`Exceptions are time-bound, so expired items become active again and visible. Closing, auto-renewing, or deleting would hide the risk.`},

{d:"AU",s:`A remediation owner believes a vulnerability was reported incorrectly. What should they do?`,
o:[`Request a false positive with evidence`,`Close the vulnerable item without telling anyone`,`Delete the vulnerability from the NVD import`,`Ask the scanner vendor to remove the CI`],
a:[0],
v:true,
e:`False positive requests are reviewed and approved, documenting why the finding is wrong. Silent closure, editing NVD data, or asking vendors to remove CIs aren't appropriate.`},

{d:"AU",s:`Why do exception and false positive requests require approval?`,
o:[`They accept risk, which needs accountable approval`,`The platform can't save requests without an approver`,`Approvals make the scanner stop finding the issue`,`Approvals lower the item's CVSS score automatically`],
a:[0],
e:`Accepting risk or dismissing a finding is a decision with consequences, so it needs accountable approval. Approvals don't change scanners or scores.`},

{d:"AU",s:`What can exception rules automate?`,
o:[`Applying exceptions to matching items`,`Approving every exception request without review`,`Deleting items that already have an exception`,`Lowering risk scores for all items in a group`],
a:[0],
v:true,
e:`Exception rules apply pre-approved exceptions consistently — for example, for a known compensating control. They don't bypass approval policy, delete items, or change scores.`},

{d:"AU",s:`How can Flow Designer help automate vulnerability remediation?`,
o:[`By creating changes from remediation tasks`,`By rewriting the scanner's detection logic`,`By publishing new CVEs to the NVD`,`By changing CVSS scores for older vulnerabilities`],
a:[0],
e:`Flows can open changes, notify owners, request approvals, and trigger patch tools. They don't modify scanners, the NVD, or CVSS.`},

{d:"AU",s:`Why create a change request for a large patch deployment from a remediation task?`,
o:[`So the fix follows change control`,`Because vulnerable items can't be closed without one`,`So the scanner knows which patch was installed`,`Because change requests raise the item's risk score`],
a:[0],
v:true,
e:`Change management controls risk from the fix itself and keeps an audit trail linking remediation to vulnerabilities. Closure, scanner knowledge, and scores aren't the reason.`},

{d:"AU",s:`What does automating vulnerability close-out typically rely on?`,
o:[`Rescans confirming it's gone`,`Owners marking items closed whenever they choose`,`The remediation target date passing`,`The NVD deleting the CVE`],
a:[0],
v:true,
e:`Evidence from rescans is the reliable basis for closure. Self-closing without evidence, deadlines, or NVD changes aren't proof of remediation.`},

{d:"AU",s:`What's a good use of automated notifications in VR?`,
o:[`Alerting owners about new critical items and upcoming deadlines`,`Emailing every vulnerable item to every employee daily`,`Notifying the scanner vendor about each finding`,`Sending exception approvals to remediation owners to approve`],
a:[0],
e:`Targeted notifications drive timely action. Mass emails cause fatigue, vendors don't need your findings, and owners shouldn't approve their own exceptions.`},

{d:"AU",s:`Why might a flow escalate overdue critical vulnerabilities to a manager?`,
o:[`So overdue high-risk work gets attention`,`To punish the remediation owner publicly`,`To close the items before the audit`,`To lower the risk rating of overdue items`],
a:[0],
e:`Escalation brings management attention to overdue risk. It isn't about punishment, premature closure, or lowering ratings.`},

{d:"AU",s:`How can patch management tools connect with VR automation?`,
o:[`They can be triggered by flows that record results`,`They can replace VR's need for scanner data`,`They can approve exceptions on behalf of analysts`,`They can change NVD records for installed patches`],
a:[0],
v:true,
e:`Integrating with tools like Microsoft Configuration Manager lets VR initiate or track patching. They don't replace scanning, approve exceptions, or change the NVD.`},

{d:"AU",s:`What should an exception request include?`,
o:[`Justification, compensating controls, and an end date`,`Only the remediation owner's name and nothing else`,`A promise that the vulnerability isn't real`,`The scanner vendor's support contract number`],
a:[0],
e:`Approvers need to know why, how risk is reduced meanwhile, and when it will be revisited. A name alone, false claims, or contract numbers don't support a decision.`},

{d:"AU",s:`What's the risk of approving exceptions with no expiry?`,
o:[`The accepted risk is forgotten and never revisited`,`The exception will be deleted at the next import`,`The vulnerable item will be closed as fixed`,`The scanner will stop scanning the CI`],
a:[0],
e:`Open-ended exceptions turn temporary decisions into permanent blind spots. They don't get deleted, close items, or stop scanning.`},

{d:"AU",s:`Why automate the grouping and assignment of new vulnerable items?`,
o:[`Teams get actionable work quickly without manual triage`,`Automation removes the need for remediation owners`,`Automated grouping deletes low-risk vulnerabilities`,`It prevents scanners from finding new vulnerabilities`],
a:[0],
e:`Automation makes remediation start sooner at scale. Owners still fix things, low-risk items aren't deleted, and scanning continues.`},

{d:"AU",s:`A false positive is approved. What should prevent it from reappearing as new work after the next scan?`,
o:[`The approved state persisting across rescans`,`Deleting the finding from the scanner manually`,`Removing the CI from the CMDB`,`Raising the item's risk score`],
a:[0],
v:true,
e:`VR tracks the false positive so future detections of the same issue don't create new work. Editing scanners, deleting CIs, or raising scores is wrong.`},

{d:"AU",s:`How can automation help verify that a patch fixed a vulnerability?`,
o:[`By requesting a rescan of affected hosts after deployment`,`By closing items as soon as the change request is approved`,`By lowering the risk score once the patch is downloaded`,`By asking the owner to confirm by email`],
a:[0],
v:true,
e:`Triggered rescans confirm fixes quickly. Change approval or downloading isn't proof, and email confirmation isn't evidence.`},

{d:"AU",s:`What does "close-out" mean for a remediation task?`,
o:[`Completing it once items are resolved`,`Deleting the task and its items from the system`,`Transferring it to a different instance`,`Lowering its priority to the minimum`],
a:[0],
v:true,
e:`Close-out completes the task when all its items are resolved or formally excepted. Deleting, transferring, or reprioritizing isn't close-out.`},

{d:"AU",s:`Why use subflows for common VR automation steps?`,
o:[`To reuse logic across flows`,`Because flows can't contain more than one step`,`To hide automation from the audit trail`,`Because subflows run without any permissions`],
a:[0],
e:`Subflows centralize reusable logic. Flows can have many steps, actions are auditable, and permissions still apply.`},

{d:"AU",s:`An exception was approved for a vulnerable item, but the asset's risk later increases. What should happen?`,
o:[`The exception should be re-evaluated`,`The exception stays regardless of risk`,`The vulnerable item should be deleted`,`The asset's criticality should be lowered`],
a:[0],
e:`Exceptions assume a risk level. If risk rises — for example, an exploit appears — the decision should be revisited. Ignoring, deleting, or lowering criticality hides the change.`},

{d:"AU",s:`What's a good first automation for a new VR deployment?`,
o:[`Auto-assigning items using CI ownership`,`Auto-approving every exception request`,`Auto-deleting all low-risk vulnerabilities`,`Auto-changing CVSS scores for old CVEs`],
a:[0],
e:`Automated routing delivers quick value with low risk. Auto-approving exceptions, deleting items, or changing scores undermine the program.`},

{d:"AU",s:`How should automation handle a vulnerability that's reported fixed but reappears on the next scan?`,
o:[`Reopen it and notify the owner`,`Ignore it, since it was already closed`,`Create a security incident automatically`,`Delete the CI from the CMDB`],
a:[0],
v:true,
e:`Reappearing vulnerabilities need to be worked again. Ignoring them hides risk, and incidents or CI deletion aren't the right response.`},

{d:"AU",s:`What's the benefit of an approval workflow for false positives?`,
o:[`A second person checks the evidence first`,`It lets owners dismiss any item without needing evidence`,`It makes the scanner produce fewer findings automatically`,`It closes all other open items on the same CI`],
a:[0],
e:`Independent review prevents real vulnerabilities from being wrongly dismissed. It doesn't remove evidence requirements, change scanner output, or affect other items.`},

{d:"AU",s:`Why might a flow automatically raise a vulnerable item's priority?`,
o:[`It's being actively exploited`,`The remediation owner went on vacation`,`The scanner was upgraded to a new version`,`The item was viewed by an analyst`],
a:[0],
e:`Active exploitation changes urgency, so automation can raise priority and notify owners. Vacations, scanner upgrades, and views don't change risk.`},

{d:"AU",s:`Which is an appropriate automated action when a remediation target is about to be missed?`,
o:[`Remind the owner and their manager`,`Extend the target date by another month`,`Close the task to avoid an overdue metric`,`Lower the item's risk rating`],
a:[0],
e:`Reminders prompt action before deadlines. Silently extending dates, closing tasks, or lowering ratings distort metrics and hide risk.`},

{d:"AU",s:`How does automation support audit readiness in VR?`,
o:[`It records actions and approvals`,`It hides overdue items from auditors`,`It deletes records older than one year`,`It removes the need for exceptions`],
a:[0],
e:`Consistent records of who did what, when, and why make audits straightforward. Hiding, deleting, or skipping exceptions would fail an audit.`},

{d:"AU",s:`What should happen to vulnerable items when their remediation task's change request is cancelled?`,
o:[`They stay open for another fix`,`They close automatically as fixed`,`They're deleted with the change`,`Their risk scores drop to zero`],
a:[0],
e:`Cancelling a change doesn't fix anything, so the items remain open. Closing, deleting, or zeroing scores would be wrong.`},

{d:"AU",s:`What's the main purpose of automating Vulnerability Response workflows?`,
o:[`Shortening the time from detection to verified fix`,`Replacing scanners with ServiceNow automation`,`Reducing the number of vulnerabilities scanners report`,`Removing the need for a CMDB`],
a:[0],
e:`Automation speeds routing, remediation, and verification. It doesn't replace scanners, change detection, or remove the need for CMDB context.`},

{d:"AU",s:`Why should automated exception handling log who approved each exception?`,
o:[`Accepted risk needs clear accountability`,`Logging approvals speeds up rescans`,`Logs are needed to import NVD data`,`Logs raise the item's risk score`],
a:[0],
e:`Knowing who accepted risk is essential for governance and audits. It doesn't affect scans, imports, or scores.`},

{d:"AU",s:`What's a risk of fully automatic closure based on a single missed detection?`,
o:[`Items may close when a scan missed a host`,`The NVD may remove the CVE as a result`,`Scanners may stop working after closures`,`Remediation owners may lose their roles`],
a:[0],
v:true,
e:`A host that was offline during a scan isn't necessarily fixed, so closure logic should require reliable evidence. The other effects don't happen.`},

{d:"AU",s:`How can VR automation help with vulnerabilities in container images?`,
o:[`Notify image owners and track rebuilds`,`Patch running containers in place forever`,`Delete the container registry`,`Lower the image's risk score`],
a:[0],
v:true,
e:`Container fixes usually mean rebuilding images, so automation routes findings to image owners and tracks progress. Patching running containers isn't best practice, and the other actions are harmful.`},

{d:"DR",s:`Which metric best shows whether the vulnerability backlog is shrinking?`,
o:[`Trend of open vulnerable items by risk rating over time`,`The total number of scanners connected to the instance`,`The number of CVEs published by the NVD this month`,`The number of users with the analyst role`],
a:[0],
e:`A trend of open items by risk shows whether remediation is outpacing new findings. Scanner, NVD, and user counts don't measure your backlog.`},

{d:"DR",s:`Why use Performance Analytics for vulnerability metrics?`,
o:[`It keeps scores over time for trends`,`It replaces the scanners' detection engines`,`It patches the systems with the most findings`,`It removes exceptions that are about to expire`],
a:[0],
e:`PA keeps historical scores, so you can show improvement and compare with targets. It doesn't scan, patch, or manage exceptions.`},

{d:"DR",s:`An executive wants a quick view of overall exposure. What should the dashboard emphasize?`,
o:[`Critical and high risk items, overdue counts, and trends`,`Every vulnerable item's full description and details`,`The scanner's technical configuration settings`,`The list of CVEs published worldwide this year`],
a:[0],
e:`Executives need risk-focused summaries and trends. Full details, scanner settings, or global CVE lists don't communicate your exposure.`},

{d:"DR",s:`What does a remediation owner most need on their dashboard?`,
o:[`Their items, due dates, and overdue work`,`The organization's total CVE count since 1999`,`The configuration of the risk calculators`,`A list of scanner license expiry dates`],
a:[0],
e:`Owners need actionable lists of their work. Historical totals, calculator settings, and license dates aren't useful to them.`},

{d:"DR",s:`Which report helps show compliance with remediation targets?`,
o:[`Share of items fixed by target date`,`Number of exceptions requested by each analyst`,`Number of scanners that ran last week`,`Average length of vulnerability descriptions`],
a:[0],
e:`On-time remediation rate shows whether SLAs are being met. Exception counts by analyst, scanner runs, and description length don't.`},

{d:"DR",s:`Why break vulnerability dashboards down by assignment group?`,
o:[`To show which teams need help or attention`,`To rank employees for performance reviews`,`To hide items from other teams' views`,`To change each team's risk calculator`],
a:[0],
e:`Group breakdowns reveal where backlog or overdue work is concentrated. They aren't for ranking individuals, hiding data, or changing calculators.`},

{d:"DR",s:`What does a rising number of exceptions over time suggest?`,
o:[`The organization is accepting more risk`,`The scanners are finding fewer vulnerabilities`,`The remediation program is fully on track`,`The NVD is publishing fewer CVEs`],
a:[0],
e:`Growing exceptions can signal capacity problems or over-reliance on risk acceptance. They don't indicate fewer findings or a healthy program.`},

{d:"DR",s:`Which visualization best shows how risk is distributed across business services?`,
o:[`Open risk broken down by service`,`A list of every scanner's IP address`,`A chart of analysts' login times`,`A pie chart of CVE publication years`],
a:[0],
e:`Service-level views tie vulnerabilities to business impact. Scanner IPs, logins, and publication years don't show business risk.`},

{d:"DR",s:`What's a sensible way to share VR reports with stakeholders who don't use the platform?`,
o:[`Schedule reports to email them regularly`,`Give them all the vulnerability admin role`,`Export the whole database to a shared drive`,`Post raw scan files on the intranet`],
a:[0],
e:`Scheduled reports deliver the right information without broad access. Admin roles, database exports, and public scan files are excessive or risky.`},

{d:"DR",s:`Why track mean time to remediate separately for critical items?`,
o:[`The fastest response should go to the highest risks`,`Critical items can't be included in overall averages`,`The NVD requires a separate metric for critical items`,`Critical items are never assigned to teams`],
a:[0],
e:`Overall averages can hide slow handling of critical vulnerabilities. They can be included in totals, the NVD doesn't require it, and critical items are assigned like others.`},
  ],
};
