// ServiceNow CIS-SIR question bank source. Correct answers are listed in "a" (indexes into "o");
// tools/build-banks.js shuffles options deterministically and writes src/data/banks/servicenow-cis-sir.json.
module.exports = {
  id: "servicenow-cis-sir",
  vendor: "ServiceNow",
  code: "CIS-SIR",
  name: "Certified Implementation Specialist – Security Incident Response",
  fullLength: 60,
  minutes: 90,
  passPercent: 70,
  readinessPercent: 85,
  sectioned: false,
  note: "ServiceNow doesn't publish a cut score for CIS-SIR; community consensus puts it near 70%. Treat 85% here as your readiness bar. Items marked release-sensitive reference roles, tables, workspaces, and integration features that change between releases; verify them against your own instance.",
  domains: [{"id":"OV","name":"Security Incident Response Overview and Data Visualization","weight":"15%"},{"id":"CR","name":"Security Incident Creation and Threat Intelligence","weight":"14%"},{"id":"IN","name":"Security Incident and Threat Intelligence Integrations","weight":"14%"},{"id":"MG","name":"Security Incident Response Management","weight":"15%"},{"id":"RP","name":"Risk Calculations and Post Incident Response","weight":"12%"},{"id":"AU","name":"Automation and Standard Processes","weight":"30%"}],
  Q: [
{d:"OV",s:`What problem does Security Incident Response mainly solve for a security operations team?`,
o:[`It gives one structured, trackable process for handling security incidents`,`It replaces the SIEM by collecting and storing every raw log from the network`,`It blocks malware on endpoints without any need for endpoint security tools`,`It removes the need for analysts by closing every alert automatically`],
a:[0],
e:`SIR brings incidents from many sources into a consistent, auditable workflow with tasks, automation, and reporting. It works with SIEMs and endpoint tools rather than replacing them, and analysts still make decisions.`},

{d:"OV",s:`Which table does a security incident record extend?`,
o:[`Task`,`Incident`,`Problem`,`Configuration item`],
a:[0],
v:true,
e:`Security incidents extend task, so they inherit assignment, state, SLA, and approval capabilities. They're separate from IT incidents, which keeps sensitive security work apart.`},

{d:"OV",s:`Why are security incidents kept separate from IT service incidents?`,
o:[`Security work is sensitive and needs tighter access and a different process`,`Security incidents can't use assignment groups or other task features`,`IT incidents are stored on a different instance than security incidents`,`Security incidents are only created by external auditors, never by staff`],
a:[0],
e:`Separating them lets security teams restrict access to sensitive investigations and follow a security-specific lifecycle. Security incidents still use task features and live on the same instance.`},

{d:"OV",s:`Which framework do the default security incident states, such as analysis, contain, eradicate, and recover, follow?`,
o:[`NIST SP 800-61`,`ITIL service transition`,`ISO 9001 quality management`,`PCI DSS card data storage`],
a:[0],
v:true,
e:`SIR's default lifecycle reflects the NIST computer security incident handling phases. ITIL, ISO 9001, and PCI DSS address other topics.`},

{d:"OV",s:`What are response tasks in Security Incident Response?`,
o:[`Child tasks of an incident, assigned to people or groups for specific work`,`Separate security incidents opened for every observable found during analysis`,`Automatic emails sent to the person who reported the incident at each update`,`Reports that summarize the incident for executives once it has been closed`],
a:[0],
v:true,
e:`Response tasks break the response into assignable pieces — such as collecting logs or reimaging a laptop — tracked under the parent security incident.`},

{d:"OV",s:`Which role is typically given to analysts who work security incidents day to day?`,
o:[`A security incident analyst role (sn_si.analyst)`,`The itil role used by service desk agents`,`The admin role, so they can see every record`,`The catalog_admin role used for catalog items`],
a:[0],
v:true,
e:`SIR has its own roles — basic, analyst, manager, admin — so access follows least privilege. itil and catalog_admin don't grant security incident access, and admin is excessive.`},

{d:"OV",s:`An employee should be able to report a suspected security issue from the portal without seeing other security incidents. What supports this?`,
o:[`A record producer for reporting security incidents, available to basic users`,`Giving every employee the security analyst role so they can open incidents`,`Asking employees to email the CISO directly with every suspected issue`,`Creating an IT incident and copying it to security once it's confirmed`],
a:[0],
v:true,
e:`A reporting form lets employees submit concerns with minimal access, keeping investigations restricted. Granting analyst roles exposes data, and email or IT incidents lose structure.`},

{d:"OV",s:`Where do analysts typically work security incidents in recent releases?`,
o:[`In a security-focused workspace with its tools`,`In the classic incident form used by the IT service desk`,`In the system log, filtered for security events`,`In a knowledge base article for each incident`],
a:[0],
v:true,
e:`The Security Incident Response workspace gives analysts a purpose-built experience with incident details, observables, tasks, and related records. The other options aren't working environments for SIR.`},

{d:"OV",s:`What are observables in a security incident?`,
o:[`Artifacts like IPs, domains, URLs, and file hashes`,`Users who are watching the incident for updates`,`Dashboards that display the incident's status`,`Audit logs showing who viewed the incident`],
a:[0],
e:`Observables are technical artifacts related to an incident that can be enriched with threat intelligence and searched for elsewhere. Watchers, dashboards, and audit logs are different concepts.`},

{d:"OV",s:`What is the purpose of recording affected users and affected CIs on a security incident?`,
o:[`To show who and what is impacted, informing priority, risk, and response`,`To give the affected users access to the full investigation details`,`To automatically retire the affected CIs from the CMDB right away`,`To notify every affected user's manager that they caused the incident`],
a:[0],
e:`Affected users and CIs define the incident's scope and feed risk calculations through business criticality. They don't grant access, retire CIs, or assign blame.`},

{d:"OV",s:`A CISO wants a quick view of open security incidents by priority, category, and age. What's the best fit?`,
o:[`A security operations dashboard with reports or Performance Analytics`,`An export of every security incident to a spreadsheet each morning`,`A notification emailed for each incident as soon as it's created`,`A knowledge article updated manually by the security team`],
a:[0],
e:`Dashboards give leaders a live view and can include trends. Spreadsheets, per-incident emails, and manual articles are slow and error-prone.`},

{d:"OV",s:`Why use Performance Analytics for security metrics such as mean time to contain?`,
o:[`It tracks scores over time, so trends and targets can be measured`,`It stores the raw logs needed to investigate each incident`,`It automatically closes incidents that exceed the target`,`It replaces the need to record containment times on incidents`],
a:[0],
e:`PA collects scores on a schedule, showing whether response is improving. It doesn't store logs, close incidents, or remove the need for good data.`},

{d:"OV",s:`Which metric best shows how quickly the team stops an attack from spreading?`,
o:[`Mean time to contain`,`Number of dashboards`,`Total observables stored`,`Number of security roles`],
a:[0],
e:`Mean time to contain measures how long it takes to limit an incident's impact. Dashboard counts, observable totals, and role counts don't measure response speed.`},

{d:"OV",s:`What is the relationship between a security incident and its related IT records, such as changes or problems?`,
o:[`They can be linked, so remediation work and its tracking stay connected`,`They must be merged into one record before the incident can be closed`,`They're unrelated and can't reference each other in any way`,`They replace the security incident once remediation starts`],
a:[0],
e:`Linking related records — such as a change to patch a server — keeps remediation traceable back to the incident. They aren't merged or substituted.`},

{d:"OV",s:`Why might security incident records be visible only to a restricted group?`,
o:[`They can contain sensitive details about attacks, users, and weaknesses`,`Security records take up more storage, so fewer users can open them`,`The platform doesn't allow more than ten users to view any record`,`Only users in the same time zone can view security records`],
a:[0],
e:`Investigations may include personal data, attack details, and unpatched weaknesses, so access is tightly controlled. Storage, user limits, and time zones aren't the reason.`},

{d:"OV",s:`What does the security incident's category typically help with?`,
o:[`Driving routing, process selection, and reporting`,`Setting the analyst's password for the investigation`,`Choosing the color of the incident in lists`,`Deciding which instance stores the incident`],
a:[0],
e:`Categories such as phishing or malware drive which process and assignment apply and enable reporting. They don't affect passwords, colors, or storage.`},

{d:"OV",s:`An analyst needs to see the timeline of what happened during an incident. What helps most?`,
o:[`The incident's activity and timeline of updates, tasks, and related events`,`The system log for the whole instance, searched by the incident number`,`The CMDB Health dashboard for the affected configuration items`,`The list of users who have the security analyst role`],
a:[0],
v:true,
e:`The incident's activity and timeline views show what was done and when, which also feeds post-incident review. System logs, CMDB health, and role lists don't tell the incident's story.`},

{d:"OV",s:`What is the role of security incident priority?`,
o:[`Determining the order in which incidents should be worked`,`Determining which analyst created the incident record`,`Determining which instance the incident is stored on`,`Determining how many observables can be attached`],
a:[0],
e:`Priority reflects urgency and impact so analysts work the most important incidents first. It doesn't record creators, storage, or limits.`},

{d:"OV",s:`Which statement about SIR and Vulnerability Response is true?`,
o:[`They're separate apps that can be linked when a vulnerability is involved`,`They're the same application, so every vulnerability is also a security incident`,`Vulnerability Response replaces SIR for any incident involving malware`,`They can't share data because they use different instances`],
a:[0],
e:`Both are Security Operations applications. A security incident can reference vulnerable items when exploitation of a weakness is involved, but they serve different processes.`},

{d:"OV",s:`Who typically uses a manager-level SIR role?`,
o:[`Security leads overseeing queues and escalations`,`Every employee who reports a phishing email`,`External vendors who send threat intelligence feeds`,`Service desk agents handling password resets`],
a:[0],
v:true,
e:`Manager roles give oversight of security operations. Employees use basic reporting, vendors don't log in for feeds, and service desk agents don't need security access.`},

{d:"OV",s:`Why are SIR dashboards often split by audience, such as analyst and CISO views?`,
o:[`Different audiences need different levels of detail`,`The platform requires a separate dashboard for every security role`,`Analysts can't read charts, so their dashboards show only lists`,`CISO dashboards must be stored on a separate instance`],
a:[0],
e:`Analysts need actionable queues, while executives need trends, risk, and performance. That's a design choice, not a platform requirement.`},

{d:"OV",s:`What is the main benefit of a single security incident record that collects alerts, observables, tasks, and notes?`,
o:[`It keeps the investigation's full context in one place`,`It allows analysts to skip documentation entirely during the response`,`It lets the record be shared publicly to warn other organizations`,`It removes the need for any access controls on the security data`],
a:[0],
e:`Consolidating context speeds collaboration and handoffs and supports post-incident review. Documentation, access control, and confidentiality still matter.`},

{d:"CR",s:`Which of these is a common way security incidents are created?`,
o:[`From alerts sent by a SIEM or detection tool`,`From every login to the ServiceNow instance`,`From each new knowledge article published`,`From routine password expiry notices`],
a:[0],
e:`Detection tools, user reports, email, and analysts creating incidents manually are the usual sources. Logins, articles, and password notices aren't security incidents.`},

{d:"CR",s:`An analyst pastes an email body into a security incident. How can IPs, URLs, and hashes in it become observables?`,
o:[`Use observable extraction or parsing on the text`,`Retype each value into a separate new incident`,`Attach the email to a knowledge base article`,`Ask the reporter to send each value separately`],
a:[0],
v:true,
e:`Extraction finds observables in text and creates or links observable records, ready for enrichment. Retyping and re-requesting are slow and error-prone.`},

{d:"CR",s:`What does enriching an observable with threat intelligence provide?`,
o:[`Context such as reputation and known associations with threats`,`A new password for the user linked to the observable`,`An automatic fix for the vulnerability behind the observable`,`A guarantee that the observable is harmless to the business`],
a:[0],
e:`Enrichment adds context — is this IP known to be malicious, what's associated with this hash — which helps analysts judge severity. It doesn't change passwords, fix systems, or guarantee safety.`},

{d:"CR",s:`How is the MITRE ATT&CK framework used in security incidents?`,
o:[`To map it to adversary tactics and techniques`,`To calculate the financial cost of the incident`,`To choose which analyst will be assigned`,`To decide the incident's number format`],
a:[0],
v:true,
e:`Mapping incidents to ATT&CK tactics and techniques helps analysts understand attacker behavior and spot patterns. It doesn't calculate costs, assign analysts, or format numbers.`},

{d:"CR",s:`What is the difference between an observable and an indicator in threat intelligence?`,
o:[`An observable is an artifact; an indicator adds malicious context`,`An observable is always malicious; an indicator is always harmless`,`An indicator is a user; an observable is a configuration item`,`There's no difference; the two terms always mean the same thing`],
a:[0],
v:true,
e:`An observable is a fact, such as an IP address. An indicator ties observables to a pattern or context that suggests compromise.`},

{d:"CR",s:`Which standards are commonly used to share threat intelligence between organizations and tools?`,
o:[`STIX for describing threats and TAXII for exchanging them`,`HTML for describing threats and FTP for exchanging them`,`SQL for describing threats and SMTP for exchanging them`,`JSON for describing threats and USB for exchanging them`],
a:[0],
e:`STIX is a language for structured threat information, and TAXII is the protocol for exchanging it. Threat intelligence feeds commonly use both.`},

{d:"CR",s:`An analyst wants to know whether a malicious IP has been seen elsewhere in the environment. What capability helps?`,
o:[`A sightings search across connected security tools`,`A list filter on the user table for recent logins`,`A new knowledge article describing the IP address`,`A change request to block the IP everywhere at once`],
a:[0],
v:true,
e:`Sightings searches query connected tools, such as SIEM or EDR, for where an observable has appeared, which shows the incident's scope. Blocking may follow, but it doesn't answer where the IP was seen.`},

{d:"CR",s:`Why do many organizations create security incidents from grouped alerts instead of one incident per alert?`,
o:[`Related alerts belong to one investigation`,`The platform allows only one alert for each incident`,`Grouping alerts deletes the original detection data`,`Individual alerts can't contain any observables`],
a:[0],
v:true,
e:`Grouping related alerts avoids flooding analysts with duplicate incidents and gives a fuller picture. Alerts keep their data and can contain observables.`},

{d:"CR",s:`What role does a threat intelligence feed play in SIR?`,
o:[`It supplies intelligence used to enrich observables`,`It sends security incidents directly to every employee's inbox`,`It replaces the need for detection tools such as a SIEM`,`It stores the organization's internal incident history for audits`],
a:[0],
e:`Feeds bring in known malicious indicators and context, which enrich observables and can raise matches. They don't notify everyone, replace detection, or store internal history.`},

{d:"CR",s:`Which channel lets employees report suspicious email so it becomes a security incident?`,
o:[`Forwarding it to a monitored phishing mailbox`,`Replying to the sender and asking whether the email was legitimate`,`Deleting the email and mentioning it at the next team meeting`,`Posting the email on the company's social media pages`],
a:[0],
e:`A reporting mailbox, often fed by a "report phishing" button, lets the platform parse the email and create a security incident. Replying, deleting, or posting are unsafe or lose evidence.`},

{d:"CR",s:`How do email parsing rules help when security incidents are created from email?`,
o:[`They pull sender, subject, and URLs into fields`,`They forward every email to the analyst's personal mailbox`,`They delete any email that contains an attachment`,`They translate every email into the analyst's language`],
a:[0],
v:true,
e:`Parsing turns unstructured email into structured fields and observables that can drive automation. Forwarding, deleting, and translating aren't parsing.`},

{d:"CR",s:`What does threat intelligence help analysts decide during triage?`,
o:[`How serious it is and what to do first`,`Which analyst should receive a pay increase`,`Which ServiceNow release to upgrade to next`,`How many CIs should be in the CMDB`],
a:[0],
e:`Knowing that an observable is tied to an active campaign changes priority and response. The other options aren't triage decisions.`},

{d:"CR",s:`What does the Threat Intelligence Security Center bring to security teams?`,
o:[`A central place to manage threat intelligence, hunting, and related cases`,`A replacement for the CMDB that stores only security configuration items`,`A tool for scheduling vulnerability scans across the network`,`A dashboard that shows only the company's public website traffic`],
a:[0],
v:true,
e:`Threat Intelligence Security Center consolidates intelligence management and threat-focused workflows. It doesn't replace the CMDB, schedule scans, or monitor web traffic.`},

{d:"CR",s:`An analyst confirms that a reported email is harmless spam. What's a sensible outcome?`,
o:[`Close it with a resolution that records the finding`,`Leave the incident open in case the email turns malicious later`,`Delete the incident so it doesn't appear in any reports`,`Escalate it to the CISO because every report must be escalated`],
a:[0],
e:`Recording the outcome keeps metrics accurate and supports tuning. Leaving it open, deleting it, or escalating everything distorts operations.`},

{d:"CR",s:`What is a security incident's severity?`,
o:[`An assessment of the incident's potential harm`,`The number of analysts assigned to the work`,`The time the incident was created in the system`,`The name of the tool that detected the threat`],
a:[0],
e:`Severity reflects potential harm and, with other factors, informs priority and risk. Staffing, timestamps, and detection source are separate fields.`},

{d:"CR",s:`Why link security incidents that share the same observables?`,
o:[`It can reveal a wider campaign rather than isolated events`,`It merges all of the incidents into a single closed record`,`It assigns all of the incidents to the same employee`,`It prevents any further observables from being added`],
a:[0],
e:`Shared observables across incidents can show coordinated activity, changing how the team responds. Linking doesn't merge, reassign, or freeze records.`},

{d:"CR",s:`Why is it useful for a security incident to reference the detecting tool and its original alert?`,
o:[`It lets analysts trace back to source data and tune detection`,`It lets the detection tool close the incident on its own`,`It hides the incident from users without admin roles`,`It sets the incident's priority to critical automatically`],
a:[0],
e:`Source references let analysts pivot into the original evidence and provide feedback on false positives. They don't control closure, visibility, or priority.`},

{d:"CR",s:`A user reports a lost laptop that may hold sensitive data. How should this be handled?`,
o:[`As a security incident using a lost device process`,`As a password reset request in the IT service catalog`,`As a knowledge article for other employees to read`,`As a hardware refresh order with no security review`],
a:[0],
e:`A lost device with sensitive data is a security event, typically handled by a specific process including remote wipe and data exposure assessment.`},

{d:"CR",s:`Which observable type would a file hash be used for?`,
o:[`Identifying a specific file, like malware`,`Identifying a user's mailbox on the mail server`,`Identifying a network's subnet range`,`Identifying a website's DNS registrar`],
a:[0],
e:`Hashes uniquely fingerprint files, so they're used to check whether a file is known malware. Mailboxes, subnets, and registrars are other observable or context types.`},

{d:"CR",s:`Why should analysts avoid opening suspicious links directly from a reported email?`,
o:[`They could infect the analyst's device; use safe analysis tools instead`,`Links can only be opened by users with the admin role on the instance`,`Opening a link automatically closes the related security incident`,`Links in emails are always harmless, so there's no point in opening them`],
a:[0],
e:`Analysis should happen in safe environments, such as sandboxes or reputation lookups, rather than by clicking. The other statements are false.`},

{d:"CR",s:`An analyst opens a security incident manually after a phone call from a worried manager. What should they capture first?`,
o:[`What happened, who and what is affected, and any observables known so far`,`Only the caller's name, since everything else can be added after closure`,`A full root cause analysis before any other fields are filled in`,`The names of every employee in the manager's department`],
a:[0],
e:`Early, structured details — description, affected users and CIs, observables — drive triage, priority, and automation. Root cause comes later, and listing unrelated employees isn't useful.`},

{d:"IN",s:`Where should an implementer look first for a certified integration with a security tool such as a SIEM or EDR?`,
o:[`The ServiceNow Store`,`The ServiceNow Share site`,`A personal blog post`,`The instance's system log`],
a:[0],
e:`Store apps are reviewed and supported. Share hosts community content that isn't certified, and blogs and logs aren't integration sources.`},

{d:"IN",s:`What's the key difference between ServiceNow Store and ServiceNow Share content?`,
o:[`Store apps are certified and supported; Share content isn't`,`Share apps are certified by ServiceNow; Store content comes from anonymous users`,`Store apps are free, while Share content must always be purchased`,`There's no difference; both sites host the same apps under different names`],
a:[0],
v:true,
e:`Store applications pass certification and are supported, which matters for production security integrations. Share content can help, but carries more risk.`},

{d:"IN",s:`A SIEM integration creates security incidents from alerts. What should be configured so fields land in the right places?`,
o:[`Field mappings from alert to incident fields`,`A new custom table for each type of SIEM alert`,`A notification that emails each alert to analysts`,`A dashboard showing the SIEM's raw log volume`],
a:[0],
e:`Mapping alert fields — source, severity, hosts, users — to incident fields makes incidents useful and automation-ready. Custom tables and emails add work, and dashboards don't create records.`},

{d:"IN",s:`How do Security Operations integrations typically expose actions such as "threat lookup" or "block IP"?`,
o:[`Through capabilities implemented by each tool`,`Through client scripts added to the security incident form`,`Through knowledge articles that analysts copy and paste`,`Through system properties that store each tool's commands`],
a:[0],
v:true,
e:`The integration framework defines capabilities, and each tool's integration implements them, so playbooks can call "block IP" regardless of which firewall is behind it.`},

{d:"IN",s:`An organization uses both a commercial and an open-source threat feed. How can SIR use both?`,
o:[`Configure each as a feed source for enrichment`,`Choose one feed only, since the platform supports a single feed at a time`,`Copy the commercial feed's data into the open-source feed by hand each day`,`Store both feeds as attachments on a single knowledge article`],
a:[0],
v:true,
e:`Multiple feeds can be configured, and enrichment can draw on all of them. Manual copying and attachments don't integrate intelligence.`},

{d:"IN",s:`What does an integration with an EDR tool such as CrowdStrike or Microsoft Defender for Endpoint typically allow from SIR?`,
o:[`Retrieving endpoint details and taking actions such as isolating a host`,`Resetting every user's password in Microsoft Entra ID automatically`,`Replacing the EDR console so analysts never use it again`,`Creating new CI classes for each malware family`],
a:[0],
v:true,
e:`EDR integrations bring endpoint context into the incident and let playbooks or analysts take containment actions. They don't reset all passwords, replace the console, or create classes.`},

{d:"IN",s:`Why is it important to keep threat intelligence feeds updated on a schedule?`,
o:[`Threat data changes fast; stale data misses threats`,`Feeds stop working entirely if they aren't refreshed every hour`,`Updating feeds increases the number of licenses available`,`Old feeds automatically delete security incidents`],
a:[0],
e:`Indicators change constantly; regular updates keep enrichment and matching accurate. The other statements are false.`},

{d:"IN",s:`How does IntegrationHub support orchestration with security tools?`,
o:[`Spokes provide actions flows can call`,`It stores raw firewall logs for long-term retention`,`It replaces Security Incident Response entirely`,`It's used only for HR and payroll integrations`],
a:[0],
v:true,
e:`Spokes for security tools let automation call external actions without custom code. IntegrationHub doesn't store logs, replace SIR, or target only HR.`},

{d:"IN",s:`A security tool sits in the company's private network. How does ServiceNow typically reach it?`,
o:[`Through a MID Server inside the network`,`Through a public link emailed to analysts`,`Through each analyst's home internet`,`Through a knowledge article attachment`],
a:[0],
e:`MID Servers relay communication between the instance and internal systems securely. The other options are insecure or don't work.`},

{d:"IN",s:`Why might an organization build a custom integration instead of using a Store app?`,
o:[`When no supported integration exists`,`Because custom integrations never need maintenance`,`Because Store apps can't be used in production`,`Because custom integrations bypass access controls`],
a:[0],
e:`Custom work makes sense when there's a gap. It does need maintenance, Store apps are production-grade, and integrations should respect security.`},

{d:"IN",s:`An integration's credentials have expired, and threat lookups fail. Where would this usually show up?`,
o:[`In the integration's run logs or errors`,`In the CMDB Health score for the server class`,`In the knowledge base feedback for security articles`,`In each analyst's notification preferences`],
a:[0],
e:`Integration logs and capability errors reveal authentication failures. CMDB health, knowledge feedback, and preferences don't track integrations.`},

{d:"IN",s:`Why might a block request to a firewall require approval before it runs?`,
o:[`Blocking the wrong address could disrupt legitimate business traffic`,`Firewalls can only accept requests that are approved by auditors`,`Approvals are required for every action the platform takes`,`Approvals make the block take effect faster on the firewall`],
a:[0],
v:true,
e:`Containment actions can cause outages, so many organizations require a human check for high-impact blocks. Not every action needs approval, and approval doesn't speed things up.`},

{d:"IN",s:`What does a vulnerability scanner integration add to security incident investigations?`,
o:[`Whether affected hosts have known weaknesses that may have been exploited`,`A list of all employees who have completed security awareness training`,`The financial value of each affected server from the asset register`,`An automatic approval for every pending change on affected hosts`],
a:[0],
e:`Knowing a host has an unpatched, exploitable vulnerability can explain how an attacker got in. Training records, asset values, and change approvals come from elsewhere.`},

{d:"IN",s:`Why integrate SIR with identity systems such as Microsoft Entra ID or Active Directory?`,
o:[`To look up users and disable compromised accounts`,`To copy every security incident into the user's personal email inbox`,`To give all affected users the security analyst role during response`,`To delete user accounts as soon as they're added to an incident`],
a:[0],
e:`Identity integrations provide context and containment actions for account compromise. Copying incidents, granting analyst roles, or deleting accounts automatically would be harmful.`},

{d:"IN",s:`A SIEM sends the same alert many times. What helps avoid duplicate security incidents?`,
o:[`Deduplication or correlation rules`,`Turning off the SIEM integration until the alerts stop`,`Deleting duplicates manually at the end of each week`,`Raising every duplicate's priority to critical`],
a:[0],
v:true,
e:`Correlation and dedup rules attach repeats to one incident. Disabling the integration loses detections, manual cleanup wastes time, and raising priority adds noise.`},

{d:"IN",s:`What should be considered before connecting a new threat feed?`,
o:[`Its reliability, relevance, and data volume`,`Whether its logo matches the company's brand colors`,`Whether it's hosted in the same city as the instance`,`Whether its data can be printed on a single page`],
a:[0],
e:`Noisy or low-quality feeds create false positives and load. Branding, location, and printability are irrelevant.`},

{d:"IN",s:`What can sandbox integrations, which detonate files safely, provide during an investigation?`,
o:[`A behavioral analysis of a file without risking production`,`A permanent copy of every file sent to the company by email`,`A backup of the analyst's laptop before the investigation starts`,`A replacement for the organization's antivirus software`],
a:[0],
e:`Sandboxes run suspicious files in isolation and report behavior, helping analysts judge whether a file is malicious. They aren't archives, backups, or antivirus replacements.`},

{d:"IN",s:`Why should integrations use dedicated service accounts with limited permissions?`,
o:[`To limit damage if the account is misused and to keep actions auditable`,`Because service accounts don't need passwords or other credentials`,`Because personal accounts can't be used with any external system`,`To give the integration administrator rights across every tool`],
a:[0],
e:`Least-privilege service accounts reduce risk and make it clear which actions the integration took. They still need credentials, and broad admin rights defeat the purpose.`},

{d:"IN",s:`A newly installed integration should be validated before go-live. What's a sensible test?`,
o:[`Run its capabilities on test data and check mappings`,`Turn it on in production and wait to see if analysts complain`,`Check only that the app's icon appears in the Store`,`Assume it works because it was downloaded from the Store`],
a:[0],
e:`Testing capabilities and mappings with safe data catches configuration problems before they affect real incidents. Waiting for complaints or assuming success is risky.`},

{d:"IN",s:`How can SIR receive security events from Event Management?`,
o:[`Alert rules can create security incidents from qualifying alerts`,`Event Management deletes alerts so SIR can recreate them`,`Analysts copy each alert's text into a new incident by hand`,`SIR can't receive events from Event Management at all`],
a:[0],
v:true,
e:`Event Management alerts that meet security criteria can create security incidents automatically, linking operational monitoring with security response.`},

{d:"IN",s:`Why might an organization share selected intelligence with an industry ISAC?`,
o:[`It helps peers defend against the same threats`,`Regulators require every security incident to be published publicly`,`ISACs pay organizations for every incident they report`,`Sharing removes the need to investigate the incident internally`],
a:[0],
e:`Information sharing communities let organizations warn each other about active threats. It's voluntary in most cases, isn't paid, and doesn't replace investigation. Security tags such as TLP help control what's shared.`},

{d:"MG",s:`What does a process definition control in Security Incident Response?`,
o:[`The lifecycle states and steps for a type of incident`,`The color scheme used on the security incident form`,`The list of users who can log in to the instance`,`The order in which threat feeds are downloaded`],
a:[0],
v:true,
e:`Process definitions define which states and steps apply, so different incident types can follow suitable lifecycles. Colors, logins, and feed order are unrelated.`},

{d:"MG",s:`Phishing incidents should follow a different process from malware incidents. How is the right process chosen?`,
o:[`Process selection rules based on conditions such as category`,`The analyst types the process name in the description field`,`The SIEM decides which process applies before sending alerts`,`Every incident uses one process, so no selection is needed`],
a:[0],
v:true,
e:`Selection rules match incident conditions to the appropriate process definition automatically.`},

{d:"MG",s:`What are security tags used for?`,
o:[`Classifying and controlling sharing, such as TLP`,`Labeling physical laptops with asset tags in the CMDB`,`Changing the security incident number prefix`,`Granting users the admin role for a single incident`],
a:[0],
v:true,
e:`Security tags categorize incidents and can restrict access or sharing — for example, Traffic Light Protocol tags. They aren't asset labels, numbering, or role grants.`},

{d:"MG",s:`An incident involves an executive and must be visible only to a small investigation team. What helps?`,
o:[`A restricting security tag or access control that limits who can see it`,`Changing the incident's category to "general" so nobody notices it`,`Emailing the details to the team instead of recording them`,`Deleting the incident after the investigation is complete`],
a:[0],
v:true,
e:`Restricting tags or ACLs keep sensitive incidents on the platform with tight access. Recategorizing, using email, or deleting loses control and evidence.`},

{d:"MG",s:`How can security incidents be assigned to the right group automatically?`,
o:[`With assignment rules based on category, affected CI, or other conditions`,`By assigning every incident to the CISO, who then redistributes them`,`By letting the person who reported the incident choose an analyst`,`By rotating incidents among all employees in alphabetical order`],
a:[0],
e:`Assignment rules route incidents by conditions, so specialists get the right work quickly. Funneling through the CISO, letting reporters choose, or rotating at random doesn't work.`},

{d:"MG",s:`A security incident is escalating and needs leadership attention. What should happen?`,
o:[`Follow the escalation path, raising priority and notifying people`,`Close the incident and open a new one with a different number`,`Remove all response tasks so the incident is simpler to read`,`Wait until the end of the week to report it in a status meeting`],
a:[0],
e:`Defined escalation paths make sure the right people know quickly. Reopening, deleting tasks, or waiting hides the problem.`},

{d:"MG",s:`What should determine a security incident's priority?`,
o:[`The severity, business impact, and affected assets`,`The alphabetical order of the reporter's surname`,`The number of characters in the incident description`,`The time of day the incident happened to be created`],
a:[0],
e:`Priority should reflect real risk to the business. Names, description length, and creation time don't.`},

{d:"MG",s:`Why use SLAs on security incidents?`,
o:[`To track whether response meets agreed targets`,`To bill the business for each security incident`,`To automatically close incidents after a fixed time`,`To prevent analysts from changing the priority`],
a:[0],
e:`SLAs measure timeliness and highlight incidents at risk of breaching targets. They don't bill, close, or lock records.`},

{d:"MG",s:`Several analysts are working different parts of one investigation. How should the work be split?`,
o:[`Into response tasks assigned to each analyst or group`,`Into separate security incidents for each analyst`,`Into comments on a single knowledge article`,`Into personal notes stored outside the platform`],
a:[0],
e:`Response tasks keep work under one incident while making each piece assignable and trackable. Splitting into separate incidents or working off-platform fragments the investigation.`},

{d:"MG",s:`An incident turns out to be a false positive. What should the analyst do?`,
o:[`Close it as a false positive and feed back to tune detection`,`Delete the incident so it doesn't affect security metrics`,`Leave it open indefinitely in case it becomes real later`,`Reassign it to the service desk as an IT incident`],
a:[0],
e:`Recording false positives improves metrics and lets detection rules be tuned. Deleting, leaving open, or reassigning loses that value.`},

{d:"MG",s:`What is the purpose of a security incident's "contain" phase?`,
o:[`To limit the incident's spread before eradicating it`,`To write the post-incident report for executives`,`To calculate the cost of the incident for finance`,`To close the incident as quickly as possible`],
a:[0],
e:`Containment stops things getting worse — isolating hosts, blocking IPs — before eradication removes the threat and recovery restores service.`},

{d:"MG",s:`Which phase follows containment in the NIST-based lifecycle?`,
o:[`Eradicate`,`Analysis`,`Draft`,`Closed`],
a:[0],
v:true,
e:`After containment, eradication removes the threat, followed by recovery and review. Analysis comes before containment.`},

{d:"MG",s:`How can managers see whether their team's queues are overloaded?`,
o:[`With workload views or reports of open incidents and tasks by assignee`,`By asking each analyst to send a daily email with their task count`,`By counting the number of observables stored on the instance`,`By checking how many threat feeds are configured`],
a:[0],
e:`Workload reporting shows who has what and where delays are building. Emails are slow, and observable or feed counts don't reflect workload.`},

{d:"MG",s:`Who should be able to change a security incident's state to closed?`,
o:[`Authorized security staff, per process and roles`,`Any employee who reported the incident through the portal`,`Any user who can see the incident in a list`,`External vendors who provided threat intelligence`],
a:[0],
v:true,
e:`Closure should be controlled by role and process, so incidents aren't closed prematurely. Reporters, viewers, and vendors shouldn't close them.`},

{d:"MG",s:`What is the value of using templates for common response tasks?`,
o:[`Consistent, complete steps for recurring incidents`,`Templates let analysts skip documenting what they did`,`Templates hide tasks from the security manager`,`Templates make every incident the same priority`],
a:[0],
e:`Templates standardize response steps, reducing missed actions. They don't remove documentation, hide work, or set priority.`},

{d:"MG",s:`An analyst needs input from the legal team about notifying regulators. How should this be handled?`,
o:[`Create a response task or request assigned to legal, linked to the incident`,`Copy the full incident into an email and forward it to the whole company`,`Add the legal team members as security analysts for the rest of the year`,`Decide alone and record the decision after the deadline has passed`],
a:[0],
e:`A linked task keeps the request tracked and the conversation on the record. Broadcasting details, granting excess roles, or acting alone are inappropriate.`},

{d:"MG",s:`Why might certain incidents need a dedicated major security incident process?`,
o:[`High-impact incidents need tighter coordination and leadership`,`Major incidents are stored in a different instance from minor incidents`,`Major incidents don't need any documentation or post-incident review`,`Only external consultants can work on major security incidents`],
a:[0],
e:`Large incidents involve many teams, executives, and often external parties, so a structured major incident approach helps. They still need documentation and review.`},

{d:"MG",s:`What's a good reason to add watchers to a security incident?`,
o:[`Stakeholders get updates without being assigned the work`,`Watchers automatically gain the security admin role`,`Watchers can close the incident on the analyst's behalf`,`Watchers replace the need for response tasks`],
a:[0],
e:`Watch lists keep the right people informed. They don't grant roles, closure rights, or replace task assignment. Consider sensitivity before adding watchers.`},

{d:"MG",s:`What does reopening a closed security incident usually indicate?`,
o:[`The threat wasn't fully resolved after all`,`The incident was closed by mistake in the wrong instance`,`The analyst wants to change the incident's number`,`The reporter wants a copy of the incident report`],
a:[0],
e:`Reopening typically means the issue recurred or wasn't fully eradicated. Instance mix-ups, number changes, and report requests aren't reasons to reopen.`},

{d:"MG",s:`What is the benefit of using the security workspace's list and record views over the classic UI for analysts?`,
o:[`The workspace puts context and actions together, speeding work`,`The workspace removes the need for any access controls on security data`,`The workspace stores incidents in a separate, faster database`,`The classic UI can't display security incidents at all`],
a:[0],
v:true,
e:`Workspaces bring together related records, observables, and actions in one place. Access controls still apply, data is stored the same way, and classic forms still work.`},

{d:"MG",s:`Why should security incident categories and subcategories be kept consistent?`,
o:[`So routing, selection, and reporting stay reliable`,`So the database uses less storage for each record`,`So incidents can be shared publicly without review`,`So analysts don't need any training on categories`],
a:[0],
e:`Consistent categorization drives automation and accurate metrics. Storage, public sharing, and training aren't the reasons.`},

{d:"MG",s:`An incident affects a business-critical application. Who should typically be informed?`,
o:[`The application owner and business stakeholders`,`Every employee in the company, by broadcast email`,`Only the analyst who first opened the incident`,`External customers, before the investigation starts`],
a:[0],
e:`Owners and stakeholders need to know so they can support response and make business decisions. Broadcasts, silence, and premature external notice are inappropriate.`},

{d:"MG",s:`An analyst is going off shift in the middle of an active investigation. What makes the handoff smooth?`,
o:[`Up-to-date work notes, task status, and observables on the incident`,`A private message to one colleague that isn't recorded anywhere`,`Leaving the incident assigned to the absent analyst overnight`,`Closing the incident and opening a new one the next morning`],
a:[0],
e:`Keeping the record current lets the next analyst pick up exactly where work stopped. Unrecorded messages, idle assignments, and reopening as new records break continuity.`},

{d:"RP",s:`What do security incident calculator groups do?`,
o:[`Set fields such as business impact, priority, or risk based on defined rules`,`Group analysts into teams based on their certifications and experience`,`Calculate the license cost of the Security Operations applications`,`Combine several security incidents into a single incident record`],
a:[0],
v:true,
e:`Calculators evaluate conditions and set values such as impact, priority, and risk score, making scoring consistent. They don't form teams, compute licensing, or merge incidents.`},

{d:"RP",s:`Why does SIR depend on accurate CMDB data for risk calculations?`,
o:[`Affected CIs' business criticality feeds the risk score`,`The CMDB stores every security incident's raw evidence and logs`,`The CMDB decides which analyst receives each incident`,`Risk calculations only work for incidents with no affected CIs`],
a:[0],
e:`If a compromised server supports a critical service, the incident's risk should reflect that, and that comes from CMDB data. The CMDB doesn't store evidence or assign analysts.`},

{d:"RP",s:`Two incidents have the same severity, but one affects a payroll system and the other a test server. How should risk differ?`,
o:[`The payroll incident should score higher because of business criticality`,`Both must score the same because their severity is the same`,`The test server incident should score higher because it's less protected`,`Risk should be decided by whichever incident was reported first`],
a:[0],
e:`Risk combines severity with business impact. A critical business system raises risk, while a test server usually lowers it. Report order is irrelevant.`},

{d:"RP",s:`What is the main purpose of a post-incident review?`,
o:[`To learn what happened and improve controls`,`To identify which employee should be disciplined`,`To delete the incident's evidence once it's closed`,`To bill the affected business unit for response time`],
a:[0],
e:`Post-incident reviews focus on lessons learned and improvements. Blame, evidence destruction, and billing aren't the purpose.`},

{d:"RP",s:`How does SIR typically collect input for a post-incident review?`,
o:[`With a review questionnaire plus the incident record`,`With an anonymous public survey posted on the company's website`,`With a phone call to each analyst that isn't documented`,`With a random sample of unrelated closed incidents`],
a:[0],
v:true,
e:`Review questionnaires (assessments) gather structured input, and the report pulls in the incident's timeline and details. Public surveys and undocumented calls lose value.`},

{d:"RP",s:`What should a post-incident report usually include?`,
o:[`A timeline, impact, actions, root cause, and fixes`,`Only the incident number and the name of the analyst who closed it`,`Every raw log line collected during the investigation`,`The personal contact details of every employee affected`],
a:[0],
e:`Reports summarize what happened and what to change. A bare number is too little, raw logs are too much, and personal details should be minimized.`},

{d:"RP",s:`After a post-incident review recommends changes, how should they be tracked?`,
o:[`As follow-up tasks with owners and due dates`,`As a note in the closed incident's description`,`As a verbal agreement at the review meeting`,`As a new security incident for each recommendation`],
a:[0],
e:`Actionable follow-ups with owners make sure improvements happen. Notes and verbal agreements are easily lost, and recommendations aren't incidents.`},

{d:"RP",s:`Which incidents should get a full post-incident review?`,
o:[`Significant incidents, based on defined criteria`,`Every false positive, regardless of how minor it was`,`Only incidents that were reported by external customers`,`None, because reviews slow down the security team`],
a:[0],
v:true,
e:`Defined criteria focus review effort where learning matters most. Reviewing every false positive wastes time, and skipping reviews forgoes improvement.`},

{d:"RP",s:`What does "business impact" on a security incident represent?`,
o:[`How much the incident affects business operations, data, or reputation`,`How many analysts the business has assigned to security operations`,`How long the business has been a ServiceNow customer`,`How many CIs the business has stored in the CMDB`],
a:[0],
e:`Business impact captures consequences for the organization and informs priority and risk. Staffing, tenure, and CI counts aren't impact.`},

{d:"RP",s:`A risk score is calculated automatically, but an analyst knows the incident is more serious. What's appropriate?`,
o:[`Adjust inputs or override per process, documenting why`,`Leave the score alone even though it's known to be wrong`,`Delete the incident and create a new one with a higher score`,`Change the affected CI's class so the score increases`],
a:[0],
v:true,
e:`Calculators help consistency, but judgment matters; documented adjustments keep both. Leaving a known-wrong score, recreating incidents, or tampering with CMDB data is wrong.`},

{d:"RP",s:`How can lessons from post-incident reviews improve future response?`,
o:[`By updating playbooks, process definitions, and detection rules`,`By deleting the reviewed incidents to keep metrics clean`,`By assigning the next incident to the same analyst every time`,`By lowering the priority of similar incidents in future`],
a:[0],
e:`Feeding lessons into playbooks, processes, and detection is how response gets better. Deleting incidents, fixed assignment, or lowering priority don't improve anything.`},

{d:"RP",s:`What does Event Management contribute to post-incident analysis?`,
o:[`Correlated alerts and timing for the timeline`,`A replacement for the post-incident questionnaire`,`Automatic approval of follow-up changes`,`The financial cost of the incident`],
a:[0],
e:`Alert data and timestamps help build the incident timeline. It doesn't replace reviews, approve changes, or calculate costs.`},

{d:"RP",s:`Why is consistent risk scoring valuable across all security incidents?`,
o:[`It lets incidents be compared and prioritized fairly`,`It guarantees that no incident will ever be scored as critical`,`It lets analysts skip triage because the score decides everything`,`It hides incidents with low scores from the CISO's dashboards`],
a:[0],
e:`Consistent scoring supports fair prioritization and trend reporting. It doesn't cap scores, replace judgment, or hide incidents.`},

{d:"RP",s:`Which CI attribute most directly feeds business criticality into SIR risk calculations?`,
o:[`The CI's criticality`,`The CI's serial number`,`The CI's purchase date`,`The CI's display name`],
a:[0],
e:`Business criticality on CIs and services tells SIR how much the business depends on them. Serial numbers, purchase dates, and names don't express importance.`},

{d:"RP",s:`What should happen to evidence collected during an incident after closure?`,
o:[`Retain it per policy, protecting integrity`,`Delete it immediately to save storage space`,`Share it publicly to help other organizations`,`Give it to the affected users to keep`],
a:[0],
e:`Evidence may be needed for legal, regulatory, or follow-up reasons, so it's retained per policy with integrity controls. Deleting or sharing it publicly is inappropriate.`},

{d:"RP",s:`Why compare risk scores before and after containment?`,
o:[`It shows how much response reduced risk`,`It decides whether the analyst passed probation`,`It sets the incident's number for future reference`,`It determines which threat feed to subscribe to`],
a:[0],
v:true,
e:`A drop in risk after containment shows the response worked and supports decisions about closure. The other options are unrelated.`},

{d:"RP",s:`A review finds that detection was slow because logs from a key system weren't collected. What's the right follow-up?`,
o:[`Onboard that system's logs to the SIEM`,`Note the gap and wait for the next incident to happen`,`Lower the system's business criticality in the CMDB`,`Close the review without any recommendations`],
a:[0],
e:`Closing visibility gaps is a classic post-incident improvement. Waiting, downgrading criticality, or ignoring the finding leaves the risk in place.`},

{d:"RP",s:`What is a "lessons learned" meeting most useful for?`,
o:[`Agreeing what went well and what to change`,`Assigning blame to the person who clicked the link`,`Reading the incident's raw logs aloud to the team`,`Approving the analyst's vacation requests`],
a:[0],
e:`Blameless lessons-learned discussions surface practical improvements. Blame discourages reporting, and the other options aren't the meeting's purpose.`},

{d:"AU",s:`What is a playbook in Security Incident Response?`,
o:[`A guided, often automated set of response activities`,`A spreadsheet listing every employee's phone number for emergencies`,`A report that shows how many incidents each analyst closed`,`A knowledge article describing the history of the SOC team`],
a:[0],
v:true,
e:`Playbooks define and guide response steps — some automated, some manual — so analysts respond consistently. Contact lists, reports, and history articles aren't playbooks.`},

{d:"AU",s:`Which tool is commonly used to build automation for security incidents in current releases?`,
o:[`Workflow Studio (Flow Designer)`,`The legacy client script editor`,`The CMDB CI Class Manager`,`The Service Portal page designer`],
a:[0],
v:true,
e:`Flows and playbooks are built in Workflow Studio (Flow Designer). Client scripts, Class Manager, and portal design aren't automation tools for SIR.`},

{d:"AU",s:`What is a good first candidate for automation in a SOC?`,
o:[`Repetitive steps like enriching phishing observables`,`Rare, complex investigations that need deep expert judgment every time`,`Decisions to notify regulators about a data breach`,`Hiring decisions for new security analysts`],
a:[0],
e:`Repetitive, well-understood steps give the best return and lowest risk. Complex judgment calls, legal decisions, and hiring stay human.`},

{d:"AU",s:`In a user-reported phishing process, what can be automated after the email is parsed?`,
o:[`Extracting URLs and checking their reputation`,`Firing the employee who received the email`,`Deleting the reporting user's mailbox`,`Publishing the email on the company intranet`],
a:[0],
e:`Automation can extract observables, enrich them, score the report, and even search for and remove similar emails. Disciplinary action, mailbox deletion, and publishing are inappropriate.`},

{d:"AU",s:`A phishing report is confirmed malicious. What automated follow-up action is commonly added?`,
o:[`Search for and remove the same email from other mailboxes`,`Send the phishing email to every employee as a warning`,`Reset passwords for every employee in the company`,`Disable the company's email system for a full day`],
a:[0],
e:`Finding and pulling the same message from other inboxes limits exposure. Resending it, mass password resets, or shutting down email are disproportionate.`},

{d:"AU",s:`Why keep a human approval step before some automated containment actions?`,
o:[`High-impact actions can disrupt the business`,`The platform can't take any action without approval`,`Approvals make automation run faster`,`Approvals are needed to create response tasks`],
a:[0],
e:`Approval gates balance speed with safety for disruptive actions. Many low-risk steps run without approval, and approvals don't speed anything up.`},

{d:"AU",s:`What triggers a security incident flow?`,
o:[`An incident being created or changing state`,`A user changing their profile photo in the portal`,`An administrator opening the system properties list`,`A report being exported to a spreadsheet`],
a:[0],
e:`Flows start on record events or conditions, such as a new phishing incident. The other events aren't relevant triggers.`},

{d:"AU",s:`What are standard processes in Security Incident Response?`,
o:[`The predefined responses for common incident types`,`The list of ServiceNow releases that support SIR`,`The default password policy for security analysts`,`The legal terms for sharing intelligence with partners`],
a:[0],
e:`Standard processes give consistent, often automated handling for frequent incident types. Releases, passwords, and legal terms are separate topics.`},

{d:"AU",s:`How can automation help with alert fatigue?`,
o:[`By enriching, correlating, and closing clear false positives`,`By hiding all alerts from analysts until the end of each day`,`By sending every alert to the CISO instead of the analysts`,`By turning off detection rules that fire more than once a week`],
a:[0],
e:`Automated triage reduces noise while keeping evidence. Hiding alerts, redirecting them, or disabling detection increases risk.`},

{d:"AU",s:`Why should automated steps record what they did on the security incident?`,
o:[`So analysts and auditors can see actions taken and their results`,`Because recorded steps run faster than unrecorded ones`,`Because flows can't run unless they write to the description`,`So the incident is hidden from other analysts`],
a:[0],
e:`An audit trail of automated actions supports investigation, review, and compliance. Recording doesn't change speed or visibility.`},

{d:"AU",s:`A playbook needs to run the same enrichment steps for several incident types. How should it be built?`,
o:[`As a reusable subflow each playbook calls`,`By copying the steps into every playbook separately`,`As a client script on the incident form`,`As a scheduled report emailed to analysts`],
a:[0],
e:`Reusable subflows and actions keep logic in one place. Copying creates drift, and client scripts or reports don't orchestrate.`},

{d:"AU",s:`What's the risk of fully automating responses without testing?`,
o:[`Faulty automation can take wrong actions at scale`,`Untested automation runs too slowly to be useful`,`Untested automation can't be turned on in production`,`There's no risk; automation is always correct`],
a:[0],
e:`Automation multiplies mistakes as well as successes. Test with safe data and consider approval gates for disruptive steps.`},

{d:"AU",s:`What can automation do when a new security incident is created from a SIEM alert?`,
o:[`Extract and enrich observables, score, and assign it`,`Write the post-incident report before any analysis begins`,`Close the incident automatically in every case`,`Ask the SIEM vendor to investigate the incident`],
a:[0],
e:`Early automation prepares the incident for an analyst with context, scoring, and routing. Writing reports early or auto-closing everything isn't appropriate.`},

{d:"AU",s:`Why might a playbook include manual tasks alongside automated ones?`,
o:[`Some steps need human judgment, such as deciding to notify customers`,`Manual tasks are required because flows can't run more than one step`,`Manual tasks make the playbook run faster than automation does`,`Manual tasks hide the playbook from the incident record`],
a:[0],
e:`Playbooks mix automated and human steps, guiding analysts through decisions that need judgment.`},

{d:"AU",s:`How can automation help meet response SLAs?`,
o:[`By triaging and routing instantly, so analysts start sooner`,`By pausing SLA timers whenever an incident is automated`,`By changing SLA targets to match current response times`,`By deleting incidents that are close to breaching their SLA`],
a:[0],
e:`Automation removes delays at the start of the process. Pausing timers, changing targets, or deleting records just hides poor performance.`},

{d:"AU",s:`A malware incident's playbook should isolate the affected host only if the risk score is high. How is this modeled?`,
o:[`With a condition in the flow that checks the risk score before isolating`,`By isolating every host involved in any incident, regardless of risk`,`By asking the user who owns the host whether it should be isolated`,`By isolating the host only after the incident has been closed`],
a:[0],
e:`Flow logic branches on conditions such as risk, so actions fit the situation. Always isolating, asking end users, or acting after closure are poor designs.`},

{d:"AU",s:`What is the benefit of starting with ServiceNow's out-of-box security processes rather than building from scratch?`,
o:[`They reflect best practice and can be tailored`,`They can't be changed, which prevents mistakes`,`They remove the need for any testing`,`They work without any data from the CMDB`],
a:[0],
v:true,
e:`Base processes give a strong starting point that you adapt. They can be changed, still need testing, and benefit from good CMDB data.`},

{d:"AU",s:`An analyst wants to run a lookup on one observable during an investigation, outside the playbook. What should be available?`,
o:[`On-demand actions like a threat lookup on the observable`,`Only the actions that run automatically when the incident is created`,`A request to the platform admin to run the lookup in production`,`A spreadsheet macro that queries the threat feed directly`],
a:[0],
v:true,
e:`Analysts can trigger enrichment and other capabilities on demand. Relying only on automatic actions or admins slows investigation, and macros bypass the platform.`},

{d:"AU",s:`How should automated playbooks handle failures, such as an integration timing out?`,
o:[`Handle the error, record it, and create a follow-up task`,`Ignore the failure and continue as though the step succeeded`,`Close the security incident automatically to avoid confusion`,`Delete the playbook so it doesn't run again`],
a:[0],
e:`Error handling keeps the incident accurate and gets a human involved when automation can't complete. Ignoring errors, closing incidents, or deleting playbooks are harmful.`},

{d:"AU",s:`Why measure how much time automation saves in the SOC?`,
o:[`It shows automation's value and what to do next`,`It's needed to calculate the ServiceNow license fee`,`It decides which analysts receive bonuses`,`It sets the risk score for each incident`],
a:[0],
e:`Time-saved metrics justify investment and highlight further opportunities. They don't drive licensing, compensation, or risk scores.`},

{d:"AU",s:`What does process selection ensure when a new security incident is created?`,
o:[`The incident follows the lifecycle and steps defined for its type`,`The incident is assigned to the analyst with the fewest tickets`,`The incident is shared with every connected security tool`,`The incident is given the highest priority available`],
a:[0],
v:true,
e:`Process selection matches incidents to the right process definition — for example, phishing versus data loss. Assignment, sharing, and priority are handled separately.`},

{d:"AU",s:`What should a standard process for a lost or stolen device typically include?`,
o:[`Remote wipe, data exposure review, credential resets`,`A full malware sandbox analysis of the missing device's files`,`A firewall block for every IP address the user ever accessed`,`An immediate public announcement about the lost device`],
a:[0],
e:`Device loss response focuses on securing the device and the data and accounts on it. Sandboxing a missing device isn't possible, and mass blocks or announcements are excessive.`},

{d:"AU",s:`What should a malware standard process typically include?`,
o:[`Find affected hosts, contain, remove, and verify`,`Reset the CMDB and rediscover every CI in the environment`,`Delete the affected users' accounts and create new ones`,`Ignore it if the antivirus already detected the file`],
a:[0],
e:`Malware response follows identify, contain, eradicate, recover. Resetting the CMDB or deleting accounts is excessive, and antivirus detection doesn't guarantee full removal.`},

{d:"AU",s:`Why should automated playbooks be reviewed after significant incidents?`,
o:[`To fix gaps the incident revealed`,`To delete playbooks that were used during the incident`,`To lower the priority of similar incidents next time`,`To give analysts permission to skip future playbooks`],
a:[0],
e:`Incidents show where automation helped or fell short, so playbooks improve over time.`},

{d:"AU",s:`A playbook step sends a notification to the affected user. Why do this?`,
o:[`To tell them what to do, like change a password`,`To give them access to the full investigation details`,`To let them close the incident if they agree`,`To ask them to assign the incident to an analyst`],
a:[0],
e:`Users often need to act, such as resetting credentials or reporting further suspicious activity. They shouldn't see full details, close incidents, or assign work.`},

{d:"AU",s:`What's a sensible way to roll out a new automated playbook?`,
o:[`Test it, pilot it on some incidents, then expand`,`Enable it for every incident type immediately without testing`,`Let analysts decide whether to run it on each incident at random`,`Turn off all existing processes so it's the only one that runs`],
a:[0],
e:`Gradual rollout limits the impact of mistakes. Immediate full rollout, random use, or disabling everything else is risky.`},

{d:"AU",s:`Why might automation create response tasks rather than taking direct action for some steps?`,
o:[`The step needs a specific team's expertise or access`,`Response tasks are the only way flows can communicate with the platform`,`Response tasks make the security incident close automatically`,`Response tasks prevent the incident from appearing on dashboards`],
a:[0],
e:`Some actions are performed by other teams or need human hands. Tasks route that work and track completion.`},

{d:"AU",s:`How can automation help with evidence collection?`,
o:[`By gathering logs and headers onto the incident`,`By deleting evidence that looks irrelevant to save time`,`By emailing evidence to the affected user for safekeeping`,`By storing evidence only on the analyst's laptop`],
a:[0],
e:`Automated collection is fast and consistent and keeps evidence with the incident. Deleting, emailing, or local storage break integrity and access control.`},

{d:"AU",s:`What's the advantage of using a capability such as "block IP" in a playbook instead of a tool-specific script?`,
o:[`The playbook keeps working if the firewall changes`,`Capabilities don't need any credentials to reach the firewall`,`Capabilities always run faster than scripts`,`Capabilities can't fail`],
a:[0],
v:true,
e:`Abstracting the action decouples playbooks from specific products. Credentials are still required, speed varies, and anything can fail.`},

{d:"AU",s:`An organization wants analysts to follow the same steps for every ransomware incident. What's the best approach?`,
o:[`Define a ransomware process with a guided playbook`,`Send analysts a PDF of the steps and trust them to follow it`,`Let each analyst create their own steps for each incident`,`Handle ransomware outside the platform to keep it confidential`],
a:[0],
e:`A defined process and playbook build consistency into the tool and record that steps were followed. PDFs, ad hoc steps, or off-platform handling lose consistency and evidence.`},

{d:"AU",s:`What role do flow triggers on security incident state changes play?`,
o:[`They start actions when the incident changes phase`,`They prevent the state from changing until a report is printed`,`They change the incident's number each time the state changes`,`They hide the incident from analysts during state changes`],
a:[0],
e:`State-change triggers start phase-specific automation, such as notifying stakeholders on containment. They don't block, renumber, or hide records.`},

{d:"AU",s:`Why use automation to check whether a reported email has already been reported by others?`,
o:[`To group duplicate reports into one incident`,`To punish users who report the same email more than once`,`To stop users from reporting any further suspicious emails`,`To delete the email from the phishing mailbox immediately`],
a:[0],
e:`Many users often report the same campaign. Grouping reports avoids duplicate investigations while recording everyone who received it.`},

{d:"AU",s:`What's an appropriate use of automation in the eradication phase?`,
o:[`Running and verifying cleanup through integrated tools`,`Closing the incident before any cleanup has been verified`,`Deleting the incident's observables to tidy the record`,`Lowering the incident's priority so it leaves dashboards`],
a:[0],
e:`Automated eradication runs and verifies cleanup steps. Closing early, deleting observables, or lowering priority would undermine the response.`},

{d:"AU",s:`What should happen when a standard process doesn't fit an unusual incident?`,
o:[`Analysts adapt the response and record why, and the process is reviewed later`,`Force the incident through the standard process even though it doesn't fit`,`Stop work until a new process has been formally approved`,`Delete the incident and handle it outside the platform`],
a:[0],
e:`Standard processes guide but shouldn't block effective response. Documenting deviations helps refine processes.`},

{d:"AU",s:`Why integrate automation with the CMDB in security playbooks?`,
o:[`To find owners, criticality, and dependencies`,`To delete CIs that appear in security incidents`,`To change the CMDB's identification rules automatically`,`To move affected CIs into a quarantine class`],
a:[0],
e:`CMDB data tells playbooks who to involve and how important a system is. Deleting CIs or changing CMDB configuration isn't part of response.`},

{d:"AU",s:`A playbook has an automated step to disable a compromised account. What should the playbook also do?`,
o:[`Record it and plan to restore access after recovery`,`Delete the account permanently so it can't be compromised again`,`Disable the accounts of everyone in the same department`,`Hide the action from the incident record to avoid alarming users`],
a:[0],
e:`Containment actions should be documented and reversed or handled properly after recovery. Deleting accounts, mass disabling, or hiding actions is harmful.`},

{d:"AU",s:`Why is it useful to track which playbook steps analysts skip?`,
o:[`Frequent skips can reveal poorly designed steps`,`So analysts who skip steps can be removed from the team`,`Because skipped steps automatically raise the incident's priority`,`It isn't useful; skipped steps should never be recorded`],
a:[0],
e:`Skip patterns point to process improvements. They aren't for punishment and don't change priority.`},

{d:"AU",s:`What's a good way to automate notifications to stakeholders during a major security incident?`,
o:[`Send milestone updates to defined audiences`,`Send every work note to every employee in real time`,`Notify stakeholders only after the incident has closed`,`Let each analyst decide whether to send any updates`],
a:[0],
e:`Milestone updates to the right audiences keep people informed without leaking details or flooding inboxes.`},

{d:"AU",s:`How does automation support the "recover" phase?`,
o:[`By running restoration steps and checks`,`By skipping recovery when containment has succeeded`,`By closing the incident as soon as recovery starts`,`By deleting containment actions from the record`],
a:[0],
e:`Recovery restores normal operations and confirms systems are clean, and automation can run and verify those steps. Skipping recovery or closing early is premature.`},

{d:"AU",s:`Why might a SOC automate the first-pass triage of low-severity incidents only?`,
o:[`It cuts workload where wrong decisions matter least`,`Low-severity incidents can't be handled by analysts at all`,`High-severity incidents can't be automated by the platform`,`Low-severity incidents never turn out to be serious`],
a:[0],
e:`Starting with low-risk incidents limits the impact of mistakes while freeing analysts. Analysts can handle any severity, high-severity steps can be automated carefully, and low-severity incidents can escalate.`},

{d:"AU",s:`What should a playbook do if enrichment shows an observable is linked to a known active campaign?`,
o:[`Raise priority and run the active-threat steps`,`Close the incident because the threat is already known`,`Remove the observable from the incident`,`Wait for another analyst to notice the match`],
a:[0],
e:`Known active threats warrant faster, stronger response. Closing, removing evidence, or waiting would be dangerous.`},

{d:"AU",s:`Why use subflows for common steps such as "notify the affected CI's owner"?`,
o:[`Changes made once apply everywhere the subflow is used`,`Subflows run without any connection to the incident record`,`Subflows can't be edited, which prevents mistakes`,`Subflows hide notifications from the audit trail`],
a:[0],
e:`Reusable subflows reduce duplication and simplify maintenance. They work with the record, can be edited, and are auditable.`},

{d:"AU",s:`What is the benefit of mapping automated playbook steps to NIST phases?`,
o:[`It keeps automation aligned with the lifecycle`,`It's required before any flow can be activated`,`It removes the need for analysts to change incident states`,`It lets the playbook skip the review phase`],
a:[0],
v:true,
e:`Aligning steps with phases makes progress visible and consistent with reporting. It isn't a technical requirement and doesn't skip phases.`},

{d:"AU",s:`A playbook keeps failing at the same integration step. What's the best response?`,
o:[`Fix the integration error and retest the playbook`,`Remove the step permanently and stop doing that action`,`Ask analysts to ignore the failure messages`,`Disable all playbooks until the next release`],
a:[0],
e:`Root-cause the failure and fix it. Removing needed steps, ignoring errors, or disabling all automation reduces capability.`},

{d:"AU",s:`What's the main goal of combining standard processes with automation in SIR?`,
o:[`Speeding consistent response so analysts focus on judgment`,`Replacing every security analyst with automated flows`,`Making every incident follow exactly the same steps`,`Reducing the number of incidents that are recorded`],
a:[0],
e:`Standard processes and automation handle the routine so people can focus on investigation and decisions. They don't replace analysts, force uniformity, or suppress records.`},
  ],
};
